denoland/deno_core

core/lib.rs
core/runtime/ops.rs
ops/op2/dispatch_slow.rs
ops/op2/signature.rs
ops/op2/test_cases/sync/serde_v8.out
ops/op2/test_cases/sync/serde_v8.rs

Supports `#[serde]` parameters in argument and return position.

feat(core): op2 #[serde] parameter support

---

core/runtime/jsrealm.rs
core/runtime/jsruntime.rs

Extracted from https://github.com/denoland/deno_core/pull/41.

refactor: Add methods for module handling to JsRealm

---

core/ops_builtin.rs
core/runtime/ops.rs
ops/op2/dispatch_async.rs
ops/op2/dispatch_slow.rs
ops/op2/test_cases/async/async_arg_return.out
ops/op2/test_cases/async/async_arg_return_result.out
ops/op2/test_cases/async/async_opstate.out
ops/op2/test_cases/async/async_result.out
ops/op2/test_cases/async/async_result_impl.out
ops/op2/test_cases/async/async_void.out
ops/op2/test_cases/sync/add.out
ops/op2/test_cases/sync/add_options.out
ops/op2/test_cases/sync/nofast.out
ops/op2/test_cases/sync/smi.out

fix(ops): don't coerce non-number v8 types to 0

---

core/runtime/jsruntime.rs

https://github.com/denoland/deno_core/pull/46#discussion_r1267447696

refactor: don't clone known realms when reporting

---

core/runtime/jsruntime.rs

Cloning the `known_realms` Vec in the inner loop adds a pretty significant overhead. We will need to get rid of this at some point but for now we can optimize the one-realm case.

fix(core): Avoid cloning Vec<JsRealmInner> when we only have one realm

---

.github/workflows/version_bump.yml
tools/create_pr_for_release.ts
tools/deno_core_workspace.ts
tools/deps.ts

I will probably need some back and forth to make it work.

chore: add workflow to create a release

---

core/examples/schedule_task.rs
core/extensions.rs
core/runtime/jsruntime.rs

refactor: static functions for global middleware

---

core/README.md

Updated the uris to not working documentation, please correct me if it's not valid.

docs(core): update example uris

---

Cargo.lock
Cargo.toml
core/runtime/jsruntime.rs

Fixes an unknown memory leak, possibly related to pointer compression

chore: downgrade v8 and pin

---

serde_v8/magic/v8slice.rs

This was causing the first part of large chunks in a ReadableStream to get repeated. Instead of responding with chunks ABCDEF of a large HTTP response, we'd respond with AAAAAA.
```
12:45 $ curl -D- localhost:8000 | grep "<html"
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
<html lang="en">
```
Fixes https://github.com/denoland/fresh/issues/1699

fix(serde_v8): v8slice split methods were incorrect after multiple splits

---

ops/op2/mod.rs
ops/op2/signature.rs
ops/op2/test_cases/sync/generics.out
ops/op2/test_cases/sync/generics.rs

fix(ops): support where T: Trait + 'static in generics

---

core/modules/tests.rs
core/runtime/jsruntime.rs

https://tc39.es/proposal-import-attributes/
Pretty much the same as import assertions, which are getting deprecated.

feat: support import attributes

---

core/ops_builtin.rs
core/runtime/tests/misc.rs

fix: don't eval JS while OpState is held

---

core/async_cancel.rs
core/async_cell.rs

This now passes cleanly:
```
cargo +nightly miri test -- async_cancel
cargo +nightly miri test -- async_cell
```

fix(core): Fix miri test problems to remove UB in CancelHandle

---

ops/op2/config.rs
ops/op2/dispatch_fast.rs
ops/op2/signature.rs
ops/op2/test_cases/sync/bool_result.out
ops/op2/test_cases/sync/cfg.out
ops/op2/test_cases/sync/cfg.rs
ops/op2/test_cases/sync/result_external.out
ops/op2/test_cases/sync/result_external.rs
ops/op2/test_cases/sync/result_primitive.out
ops/op2/test_cases/sync/v8_ref_option.out

Fixes #174, #185, and provides an error for #186

fix(ops): multiple fixes for #[op2]

---

ops/op2/dispatch_fast.rs
ops/op2/dispatch_slow.rs
ops/op2/signature.rs
ops/op2/test_cases/async/async_jsbuffer.out
ops/op2/test_cases/sync/buffers.out
ops/op2/test_cases/sync/buffers.rs
ops/op2/test_cases/sync/buffers_copy.out
ops/op2/test_cases/sync/smi.out
ops/op2/test_cases/sync/smi.rs

Fixes #188 and #176
Adds a small error fix for #189

feat(ops): support Option<*buffer type*> and Option<*smi*>

---

ops/op2/dispatch_slow.rs
ops/op2/test_cases/async/async_jsbuffer.out
ops/op2/test_cases/sync/buffers.out
ops/op2/test_cases/sync/buffers_copy.out
ops/op2/test_cases/sync/serde_v8.out
ops/op2/test_cases/sync/string_onebyte.out
ops/op2/test_cases/sync/string_option_return.out
ops/op2/test_cases/sync/string_return.out

fix(ops): use type_error everywhere

---

core/runtime/jsruntime.rs

Add note about thread inheritance requierments of V8 platform.
There is a follow up to be done to ensure our tests follow the new thread
inheritance requirements.

feat: add explicit JsRuntime::init_platform method

---

core/02_error.js
core/error.rs
core/ops_builtin.rs
core/ops_builtin_v8.rs
core/source_map.rs

perf: use fast ops for stack trace remapping

---

Cargo.lock
Cargo.toml
core/runtime/ops.rs
ops/op2/dispatch_fast.rs
ops/op2/test_cases/sync/buffers.out
ops/op2/test_cases/sync/buffers_copy.out

Will not pass until we get https://github.com/denoland/rusty_v8/pull/1326 pulled in

chore: add a test for empty slices

---

core/01_core.js
core/runtime/jsruntime.rs

This reverts commit b37184737dd113eaf3df46b47505e14a2fc9cbb7.

Revert "perf: Use V8 Deno builtins (#261)"

---

core/runtime/bindings.rs
core/runtime/tests/misc.rs

This reverts commit 35f029ce96cc4b70b91f5f05894b588d2a3fe878.

Revert "Use extra bindings object for V8 builtins (#284)"

---

core/runtime/jsruntime.rs
core/runtime/tests/misc.rs

Closes https://github.com/denoland/deno_core/issues/297

feat: enable Array.fromAsync

---

core/runtime/bindings.rs
core/runtime/jsruntime.rs
core/runtime/snapshot_util.rs
core/runtime/tests/jsrealm.rs

Needed for https://github.com/denoland/deno/pull/21066

Add option to control op registration during snapshot time

---

core/external.rs

One last required change to make this work in deno. Testing in https://github.com/denoland/deno/pull/21114

fix(core): fix externals package

---

core/01_core.js
core/lib.deno_core.d.ts
core/runtime/tests/jsrealm.rs

Remove knowledge of the promise ID from ref/unref code.

feat(core): add refOpPromise and unrefOpPromise

---

core/01_core.js

Fixes #313
There's a theoretical problem if we stomp over an existing promise in the promise map but this gets us to a better place.

fix(core): don't fail on 32-bit rollover of promise IDs

---

core/lib.rs
core/runtime/jsruntime.rs
core/runtime/mod.rs

Needed to solve https://github.com/denoland/deno/issues/20528 where we need to skip pumping V8 message
loop for some time.

feat: Add JsRuntime::run_event_loop2, JsRuntime::poll_event_loop2

---

core/modules/map.rs
core/runtime/jsruntime.rs

refactor: move module polling into ModuleMap

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/runtime/tests/misc.rs

These tests wiil be used in #359 but we can land them beforehand. One test returns an unexpected result.

test(core): add more intense testing around promises

---

core/modules/tests.rs
testing/integration/dyn_import_circular/a.js
testing/integration/dyn_import_circular/b.js
testing/integration/dyn_import_circular/c.js
testing/integration/dyn_import_circular/d.js
testing/integration/dyn_import_circular/dyn_import_circular.out
testing/integration/dyn_import_circular/dyn_import_circular.ts
testing/lib.rs
testing/tsconfig.json

chore: port dyn_import_circular to integration test 

---

core/01_core.js
core/lib.deno_core.d.ts
core/ops_builtin.rs
core/ops_builtin_v8.rs
core/runtime/exception_state.rs
core/runtime/jsruntime.rs
core/runtime/tests/misc.rs
core/runtime/tests/ops.rs
ops/op2/dispatch_shared.rs
testing/checkin/runtime/__init.js
testing/integration/error_rejection_catch/error_rejection_catch.out
testing/integration/error_rejection_catch/error_rejection_catch.ts
testing/lib.rs
testing/tsconfig.json
testing/unit/encode_decode_test.ts

Implements the deno_core equivalent of `rejectionhandled`.

feat(core): handledPromiseRejectionHandler

---

Cargo.lock
Cargo.toml
core/runtime/jsruntime.rs

"change-array-by-copy" is enabled by [default](https://chromium-review.googlesource.com/c/v8/v8/+/5035578)

Upgrade rusty_v8 to 0.83.0

---

core/runtime/jsruntime.rs

Needs confirmation that this fixes things.

fix(core): snapshot crash in windows

---

.github/workflows/ci-job.yml
.github/workflows/ci-lint-deps/action.yml
.github/workflows/ci-lint/action.yml
.github/workflows/ci-test-miri/action.yml
.github/workflows/ci-test-ops/action.yml
.github/workflows/ci-test/action.yml
.github/workflows/ci.yml
core/resources.rs

Drops the overall build time to ~4-6min, but also makes it more modular so we don't add more time as we're adding more steps.

chore: matrix builds

---

.github/workflows/ci.yml

chore: small fixes to publish

---

core/runtime/op_driver/futures_unordered_driver.rs
core/runtime/op_driver/joinset_driver.rs
core/runtime/op_driver/mod.rs
core/runtime/stats.rs
testing/checkin/runner/ops.rs

Add an op_exclusions filter and keep op names as `&'static str`.

feat(core): more enhancements to the stats API

---

core/modules/map.rs
core/runtime/jsruntime.rs

refactor: Add ModuleMap::mod_evaluate_sync

---

core/modules/map.rs
core/runtime/jsruntime.rs

refactor: Synthetic module gets instantiated on creation

---

core/modules/loaders.rs
core/runtime/jsruntime.rs

`ExtModuleLoader` was panicking on Drop if modules were not evaulated, but it's better to make this an explicit operation instead. This way we can get the extension errors as they happen.

feat(core): refactor ExtModuleLoader to log only when no execution errors

---

core/01_core.js
core/lib.deno_core.d.ts
core/ops_builtin.rs
testing/unit/encode_decode_test.ts

feat: Add `Deno.core.encodeBinaryString()`

---

core/extensions.rs
core/runtime/snapshot_util.rs

Let embedders warmup the snapshot using a warmup script.

feat: allow snapshot warmup

---

.github/workflows/ci-job.yml
.github/workflows/ci.yml

Add support for Github's new Linux ARM runners.

chore: linux arm64 runner

---

core/runtime/snapshot_util.rs

We need to get the index of js_handled_promise_rejection_cb before we build the struct.

fix(core): off-by-one panic in snapshot load

---

testing/checkin/runner/mod.rs

feat(checkin): Use snapshots in integration and unit tests

---

Cargo.lock
Cargo.toml
core/modules/map.rs
testing/unit/tc39_test.ts

chore: update rusty_v8 to 0.84.0

---

.github/workflows/ci-job.yml
.github/workflows/ci-lint/action.yml
core/01_core.js
core/internal.d.ts
core/lib.deno_core.d.ts
testing/checkin.d.ts
testing/checkin/runtime/__init.js
testing/checkin/runtime/throw.ts
testing/integration/error_ext_stack/error_ext_stack.out
testing/integration/error_ext_stack/error_ext_stack.ts
testing/tsconfig.json

The lint step will actually type-check checkin and all of the extension code in checkin.

chore: checkin type-checks w/tsc

---

core/web_timeout.rs

Fixes https://github.com/denoland/deno_core/issues/612
When we have an ineffective poll, we were failing to decrement the tombstone count. We also didn't check to see if the timers were consistent if polling returning `Pending`, which is why this bug slipped through the net.

fix(core): Fix subtle timer bug

---

core/modules/loaders.rs
core/modules/tests.rs
core/runtime/tests/jsrealm.rs
core/runtime/tests/misc.rs

refactor(core): StaticModuleLoader::default()

---

Cargo.lock
dcore/Cargo.toml
dcore/src/main.rs

Just to make arg parsing easier and allow to measure clap overhead in a small
and controlled environment.

feat: Add clap to dcore

---

core/runtime/setup.rs
testing/unit/tc39_test.ts

fix: Enable the Temporal API proposal by default

---

ops/op2/generator_state.rs
ops/op2/mod.rs

Appears to be an interaction between #676 and #677.

fix: lint with cargo udeps

---

.github/workflows/ci-coverage/action.yml
core/fast_string.rs
core/module_specifier.rs
core/modules/mod.rs
core/modules/module_map_data.rs
core/runtime/op_driver/mod.rs

- Fix some sketchiness in FastString that we were waiting on rusty_v8 to fix.
- Run more tests under miri, comments for those that can't

fix(core): miri tweaks

---

core/runtime/jsruntime.rs

Follow up to https://github.com/denoland/deno_core/pull/679.
It was not working correctly, I have a PR (https://github.com/denoland/deno/pull/23054) that
verifies this is now correct.

fix: don't require global WebAssembly namespace on startup

---

Cargo.lock
Cargo.toml

chore: upgrade rusty_v8 to 0.91.0

---

core/ops.rs

This reverts commit 2f0176d07f9ca2e444f9e1bcbdb2a3ee68e41b2c.
I have to revert this PR, because it blocks the V8 upgrade. Something is going wrong with your PR, because I get failures like this on CI:
```
#
#
#
#
#FailureMessage Object: 0xe1e9d77bc810
==== C stack trace ===============================
/home/runner/work/deno/deno/target/debug/deps/deno-df44c896ccd7880e(+0x610f368) [0xc0a0d3eaf368]
/home/runner/work/deno/deno/target/debug/deps/deno-df44c896ccd7880e(+0x580ad70) [0xc0a0d35aad70]
/home/runner/work/deno/deno/target/debug/deps/deno-df44c896ccd7880e(+0x58086f4) [0xc0a0d35a86f4]
/home/runner/work/deno/deno/target/debug/deps/deno-df44c896ccd7880e(+0x6493a6c) [0xc0a0d4233a6c]
/home/runner/work/deno/deno/target/debug/deps/deno-df44c896ccd7880e(+0x64880b8) [0xc0a0d42280b8] …
```

Revert "fix: Prevent  CFunctionInfo/CTypeInfo leak in OpCtx (#700)"

---

.github/workflows/ci-test/action.yml

Cuts ~7mins from mac/windows tests

chore: don't build dcore

---

core/fast_string.rs

We can avoid a clone in the extension_transpiler in the cli if we implement this.

feat: From<FastString> for Arc<str>

---

core/modules/map.rs
core/modules/mod.rs
core/modules/tests.rs

Towards https://github.com/denoland/deno/issues/24027

fix: lossily UTF8 decode module source text

---

core/ops_builtin_v8.rs
core/runtime/stats.rs
core/web_timeout.rs
testing/unit/stats_test.ts

For https://github.com/denoland/deno/pull/23842

Exclude system timers from runtime stats

---

.github/workflows/ci-job.yml

this is uncovering more problems, we will investigate later

disable V8_FORCE_DEBUG in ci

---

core/ops_builtin.rs
core/ops_builtin_v8.rs

closes #135
ref https://github.com/denoland/deno/pull/24396

fix: remove `op_arraybuffer_was_detached`

---

README.md

Hello
Fixing a broken link on the readme file

Update the link to contribution page

---

Cargo.lock
Cargo.toml
core/01_core.js
core/modules/loaders.rs
core/modules/map.rs
core/modules/mod.rs
core/ops_builtin_v8.rs
core/runtime/bindings.rs
core/runtime/jsrealm.rs
core/runtime/jsruntime.rs
core/runtime/mod.rs

allow setting `host_defined_options` for all code.

feat: host defined options

---

core/error.rs
core/runtime/bindings.rs
core/runtime/jsruntime.rs
core/runtime/v8_static_strings.rs
testing/integration/error_prepare_stack_trace/error_prepare_stack_trace.out
testing/integration/error_prepare_stack_trace/error_prepare_stack_trace.ts
testing/lib.rs

- **chore: report cause when JsStackFrame fails to deserialize**
- **fix: Error.pST callsite methods should be on prototype**

fix: Error.pST callsite methods should be on prototype

---

serde_v8/de.rs

Towards https://github.com/denoland/deno/issues/24784

fix: remove some unwraps in serde_v8

---

core/01_core.js
core/ops_builtin.rs
core/ops_builtin_v8.rs

need to put these here because they are shared between exts

feat: async context apis

---

core/error.rs
testing/integration/error_get_file_name/error_get_file_name.out
testing/integration/error_get_file_name/error_get_file_name.ts
testing/lib.rs

Refs: https://github.com/denoland/deno/issues/24869

fix: getFileName can return null

---

Cargo.lock
Cargo.toml
core/modules/map.rs
core/runtime/jsrealm.rs
core/runtime/jsruntime.rs
serde_v8/examples/basic.rs
serde_v8/tests/de.rs
serde_v8/tests/magic.rs
serde_v8/tests/ser.rs

Includes changes for deno node:vm impl

chore: upgrade rusty_v8

---

core/error.rs
testing/integration/error_get_file_name_to_string/error_get_file_name_to_string.out
testing/integration/error_get_file_name_to_string/error_get_file_name_to_string.ts
testing/lib.rs

Basically copy the fix from https://github.com/denoland/deno_core/pull/861

fix: getFileName can be null in .toString()

---

core/runtime/jsrealm.rs
core/runtime/jsruntime.rs
core/runtime/setup.rs

Removes the isolate ptr hack.
Fixes https://github.com/denoland/deno_core/issues/849

Fix isolate ptr memory leak

---

Cargo.lock
Cargo.toml
core/ops_builtin_v8.rs

includes fixes for tla bugs introduced in 12.9

fix: update rusty_v8

---

Cargo.lock
core/modules/map.rs
core/ops_builtin.rs
core/runtime/jsruntime.rs
core/runtime/tests/misc.rs
core/runtime/v8_static_strings.rs
serde_v8/utilities/Cargo.toml
testing/Cargo.toml
testing/checkin/runner/extensions.rs
testing/checkin/runner/ops_io.rs
testing/checkin/runner/ts_module_loader.rs
testing/integration/import_sync/async.js
testing/integration/import_sync/import_sync.out
testing/integration/import_sync/import_sync.ts
testing/integration/import_sync/sync.js
testing/lib.rs

Implement sync import for `require(esm)`

feat: `op_import_sync` for require(esm)

---

Cargo.lock
Cargo.toml

Closes https://github.com/denoland/deno_core/issues/955

chore: bump deno_unsync

---

ops/op2/dispatch_slow.rs
ops/op2/test_cases/async/async_stack_trace.out
ops/op2/test_cases/compiler_pass/sync.rs
ops/op2/test_cases/sync/stack_trace_scope.out
ops/op2/test_cases/sync/stack_trace_scope.rs

Fixes https://github.com/denoland/deno_core/issues/957

Fix scope usage in #[stack_trace]

---

core/modules/map.rs

We should be importing everything.

fix: import all Wasm imports

---

ops/op2/config.rs
ops/op2/mod.rs
ops/op2/test_cases/sync/object_wrap.out
ops/op2/test_cases/sync/object_wrap.rs

Needed some changes to the test runner

add macro output test for object wrap

---

dcore/src/main.rs

useful for investigating v8 things, enabling tracing, etc.
basically ripped verbatim from the cli

chore: add `--v8-flags` option to dcore

---

core/runtime/bindings.rs

We were creating them twice - once when attaching them to `Deno.core.ops`, then creating all new templates when setting up the virtual ops module.
That meant that the snapshot included two copies of each template, bloating the snapshot size and hurting snapshot deserialization time.
To fix this, just reuse the templates we've already attached to `Deno.core.ops`.
This greatly improves the impact of object wrap (and ops in general) on snapshot size and deserialization time.
statrtup perf:
with 1000 object wrap `DOMPoints` vs 1000 pure JS `DOMPoints` (`dcore-objwrap-1000-opt` is this PR)
```
❯ hyperfine -w 500 -N "./dcore-js-1000 empty.js" "./dcore-objwrap-1000 empty.js" "./dcore-objwrap-1000-opt empty.js"
Benchmark 1: ./dcore-js-1000 empty.js
Time (mean ± σ):      10.5 ms ±   0.5 ms …
```

perf: don't create duplicate function/object templates for ops

---

core/00_infra.js
core/rebuild_async_stubs.js
core/runtime/bindings.rs
ops/op2/config.rs
ops/op2/signature.rs
testing/checkin/runner/ops.rs
testing/ops.d.ts
testing/unit/resource_test.ts

```rust
impl TestObjectWrap {
#[async_method]
async fn with_async_fn(&self)  {
// ...
}
}
```

Support async methods in object wrap

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/runtime/ops.rs
core/runtime/ops_rust_to_v8.rs
core/runtime/setup.rs

allows returning any Vec/Box type which corresponds to a TypedArray

feat: implement ToV8 for all TypedArray types

---

core/ops.rs
core/runtime/bindings.rs

Reverts denoland/deno_core#1049

Revert "perf: externalize op name strings"

---

Cargo.lock
Cargo.toml
core/inspector.rs

Depends on:
https://github.com/denoland/rusty_v8/pull/1684
https://github.com/denoland/rusty_v8/pull/1685
Fixes:
https://github.com/denoland/deno/issues/27849

Fix `create_stack_trace` from empty trace

---

Cargo.lock
Cargo.toml

includes fix for stack overflow crashes

Bump V8 to 134.4.0

---

.github/workflows/ci-lint-deps/action.yml
Cargo.lock
Cargo.toml

fix: explicit resource management fixes

---

Cargo.lock
Cargo.toml
core/ops_builtin_v8.rs
ops/op2/dispatch_fast.rs
ops/op2/test_cases/sync/buffers.out
ops/op2/test_cases/sync/buffers_copy.out
ops/op2/test_cases_fail/lifetimes.stderr
serde_v8/de.rs

includes a fix to avoid ub on null slices

feat: upgrade V8 to 135

---

core/web_timeout.rs

Modify timer compaction strategy to clean up tombstones based solely on
exceeding a minimum threshold, rather than requiring tombstones to outnumber
active timers. This resolves memory leaks in scenarios with many active
timers (like WebSocket connections) where tombstones would previously
accumulate indefinitely.
Fixes https://github.com/denoland/deno/issues/27925 (once deno_core upgraded)

fix: prevent timer tombstone accumulation

---

core/feature_checker.rs
core/ops_builtin_v8.rs
core/runtime/jsruntime.rs

add apis needed for https://github.com/denoland/deno/pull/28929

feat: add needed apis for lazy init

---

ops/op2/dispatch_fast.rs
testing/ops.d.ts
testing/unit/resource_test.ts

Fix for https://github.com/denoland/deno/issues/29094

Fix correct proto unwraps in fast calls

---

Cargo.lock
Cargo.toml
core/inspector.rs

part of fix for https://github.com/denoland/deno/issues/27003

fix: add resourceNameToUrl mapping

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/async_cancel.rs
core/error.rs
core/modules/tests.rs

https://github.com/denoland/deno_error/pull/17

refactor: upgrade deno_error

---

core/cppgc.rs
core/webidl.rs

For https://github.com/denoland/deno/pull/30563

 feat(cppgc): add Member & Persistent (Ref) wrappers 
