denoland/deno_core

core/extensions.rs, core/modules/map.rs, core/runtime/jsruntime.rs
Includes changes to support https://github.com/denoland/deno/pull/19680.
`esm_with_specifiers` was added to `extension!` macro as well as
`include_js_files_with_specifiers!` macro.
=> refactor: Support specifying specifiers for extension files

Cargo.lock, core/runtime/ops.rs, ops/Cargo.toml, ops/lib.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/mod.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/clippy_allow.out, ops/op2/test_cases/sync/clippy_allow.rs, ops/op2/test_cases/sync/v8_handlescope.out, ops/op2/test_cases/sync/v8_handlescope.rs, ops/op2/test_cases/sync/v8_lifetime.out, ops/op2/test_cases/sync/v8_lifetime.rs, ops/op2/test_cases/sync/v8_ref_option.out, ops/op2/test_cases/sync/v8_ref_option.rs, ops/op2/test_cases/sync/v8_string.out, ops/op2/test_cases/sync/v8_string.rs
`op2` support for `v8::Value` and related types. Functions may take arguments of the form `&v8::String` (or `&mut v8::String`), `v8::Local<v8::String>`, or an `Option<...>` of any of these. Under the hood, the op system will check the type of the argument and automatically throw a type error if it does not match.
Implements:
Additional changes:
=> feat(core): Implement v8::XXX args and return

core/lib.rs
It seems like JsRuntimeForSnapshot cannot be created from outside of deno-core because RuntimeSnapshotOptions isn't publicly exported.
This is a port of https://github.com/denoland/deno/pull/19661
=> fix: Re-export RuntimeSnapshotOptions

core/runtime/ops.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/sync/bool_result.out, ops/op2/test_cases/sync/result_primitive.out, ops/op2/test_cases/sync/result_scope.out, ops/op2/test_cases/sync/result_scope.rs, ops/op2/test_cases/sync/result_void.out, ops/op2/test_cases/sync/serde_v8.out, ops/op2/test_cases/sync/string_cow.out, ops/op2/test_cases/sync/string_option_return.out, ops/op2/test_cases/sync/string_owned.out, ops/op2/test_cases/sync/string_ref.out, ops/op2/test_cases/sync/string_return.out, ops/op2/test_cases/sync/v8_handlescope.out, ops/op2/test_cases/sync/v8_ref_option.out, ops/op2/test_cases/sync/v8_string.out
Allows returning from functions that take a `HandleScope`
=> fix(ops): defer mut ref for ops2 scope

core/ops_builtin.rs, core/ops_builtin_v8.rs
These are all the ops I managed to migrate to `op2` macro.
=> refactor: migrate some ops_builtin_v8 to op2 macro

core/lib.rs, core/runtime/ops.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_shared.rs, ops/op2/dispatch_slow.rs, ops/op2/mod.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/v8_handlescope.out, ops/op2/test_cases/sync/v8_lifetime.out, ops/op2/test_cases/sync/v8_ref_option.out, ops/op2/test_cases/sync/v8_ref_option.rs, ops/op2/test_cases/sync/v8_string.out
Ops that are `v8::*`-style are fast-capable, so let's implement this. We start sharing a bit of code between fast and slow ops to support this.
=> feat(ops): Make v8::* ops fast-capable

core/runtime/ops.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/buffers.out, ops/op2/test_cases/sync/buffers.rs, serde_v8/lib.rs, serde_v8/magic/v8slice.rs
Adds:
- `#[buffer] &[u8]`
- `#[buffer] &mut [u8]`
TODO:
- `#[buffer] *const u8` (all primitive types) -- not recommended but used in FFI
- `#[buffer] *mut u8` (all primitive types)
- `#[buffer] bytes::Bytes`
- `#[buffer] JSBuffer`
- `#[buffer] V8Slice`
- `#[buffer] Vec<..>`
- `#[buffer] Box<[..]>`
TODO: Alternative buffer modes:
- `#[buffer(shared)]` (the default)
- `#[buffer(copy)]` 
- `#[buffer(detach)]`
=> feat(ops): Basic buffer support for op2 

core/runtime/jsruntime.rs
I accidentally provided an extension again after creating a snapshot and it cost me a bit of time. This might help someone in the future.
=> fix: better message when someone provides a module that was already included in a snapshot

core/lib.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs, core/runtime/tests/jsrealm.rs
Extracted from https://github.com/denoland/deno_core/pull/41.
Current this struct is not used.
=> refactor: Add CreateRealmOptions

Cargo.lock, core/Cargo.toml, core/benches/ops/sync.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/sync/string_cow.out, ops/op2/test_cases/sync/string_ref.out
Approximately 25% faster strings from `op` -> `op2`.
=> feat(ops): Benchmark sync ops, support for Option<numeric>, faster strings

core/modules/map.rs, core/runtime/bindings.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/tests/snapshot.rs
Extracted from https://github.com/denoland/deno_core/pull/41.
Now all `JsRealm` instances have a `ModuleMap`, but only the "main realm"
`ModuleMap` is being used.
=> refactor: Move ModuleMap to JsRealm

core/modules/map.rs, core/runtime/jsruntime.rs
Extracted from https://github.com/denoland/deno_core/pull/41.
=> refactor: Factor out stalled top-level await reporting

core/runtime/ops.rs, ops/op2/dispatch_async.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/async/async_result_impl.out, ops/op2/test_cases/async/async_result_impl.rs, ops/op2/test_cases/compiler_pass/async.rs
Supports `Result<impl Future<...>>`-style async ops like so:
```rust
#[op2(async, core)]
pub fn op_async_result_impl(
mode: u8,
) -> Result<impl Future<Output = Result<(), Error>>, Error> {
if mode == 0 {
return Err(generic_error("early exit"));
}
return Ok(async move {
if mode == 1 {
return Err(generic_error("early async exit"));
}
tokio::time::sleep(Duration::from_millis(500)).await;
if mode == 2 {
return Err(generic_error("late async exit"));
}
return Ok(());
});
}
```
=> feat(ops): op2 support for Result<impl Future<...>> 

Cargo.lock, Cargo.toml, core/Cargo.toml, ops/Cargo.toml, serde_v8/Cargo.toml
Sadly the release script is still not working correctly:
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 4 of 4 required status checks are expected.        
To https://github.com/denoland/deno_core
! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/denoland/deno_core'
error: Uncaught (in promise) Error: Exited with code: 1
throw new Error(`Exited with code: ${code}`);
^
at CommandChild.pipedStdoutBuffer (https://deno.land/x/dax@0.30.0/src/command.ts:585:17)
at eventLoopTick (ext:core/01_core.js:183:11)
```
=> chore: release v0.196.0

core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/tests/jsrealm.rs
The `JsRuntime::check_promise_rejection` method takes care of failing the event loop run if it detects any rejected promise in any realm. It does so by delegating to `JsRealmInner::check_promise_rejection` for every realm; however, the scope it passes to that method is `runtime.handle_scope()` – that is, the main realm's scope. The `JsRealmInner` method in turn uses this scope, which results in the main realm's format exception callback being called, rather than the actual realm's.
This patch fixes this by changing `JsRealmInner::check_promise_rejection` to take a `&mut v8::Isolate` rather than a `&mut v8::HandleScope`, and to call `Self::handle_scope` to create a scope in the realm, as the rest of `JsRealm` and `JsRealmInner` methods do. It also adds realm-specific tests for the format …
=> fix(realms): Call the right realm's format exception callback for promise rejections

core/fast_string.rs, core/lib.rs, core/modules/loaders.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/jsrealm.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs, core/runtime/tests/snapshot.rs
Adds the following test utilities to remove a lot of boilerplate from the deno_core tests:
- `StaticModuleLoader` to provide a set of static files that don't require the filesystem
- `CountingModuleLoader` to test resolve/prepare/load counts
- `LoggingModuleLoader` to log a list of load attempts
=> refactor(core): Introduce a StaticModuleLoader

core/runtime/jsruntime.rs, core/runtime/tests/ops.rs
Repro and fix for https://github.com/denoland/deno/issues/19903 and https://github.com/denoland/deno/issues/19455.
No perf impact seen in deno before and after.
=> fix(core): Re-run event loop after resolving ops

core/extensions.rs
You can see this done for things like https://doc.rust-lang.org/std/macro.concat.html.
Lets users pass computed expressions as long as they are computed at compile time.
Leads to better error messages if a non-literal is passed:
```rust
extension!(foo, esm_entry_point = "".to_string(),);
```
Before:
```
error: no rules expected the token `.`
--> core/extensions.rs:783:37
|
241 | macro_rules! extension {
| ---------------------- when calling this macro
...
783 | extension!(foo, esm_entry_point = "".to_string(),);
|                                     ^ no rules expected this token in macro call
|
= note: while trying to match sequence start
```
After:
```
error[E0308]: mismatched types
--> core/extensions.rs:783:35
|
288 |             const V: Option<&'static str> = …
```
=> fix(extensions): use expr instead of literal

core/extensions.rs
Mistake I made in #91. `$js` has to stay a literal to avoid parsing ambiguities, just like `$esm:literal`. cc @mmastrac
=> fix(extensions): use literal for js source in macro

core/error.rs, core/runtime/jsruntime.rs, serde_v8/magic/global.rs
The second argument to `v8::Local` can be a reference, so cloning isn't needed.
=> fix: Remove unnecessary clones in `v8::Local` constructors

core/runtime/jsruntime.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs
The way `JsRuntime::init_extension_js` initialized ESM extensions without a snapshot was by running the event loop and blocking the thread ntil there were no more tasks. This works fine for the main realm, because it is created before any user code can start any async ops. However, other realms may be created while async ops are running, which would make realm creation hang until those ops are resolved.
Since extensions are not expected to use top-level await, there would be no need to run the entire event loop for modules to resolve; calling `JsRealm::evaluate_pending_module` would be enough. If the module is not resolved after calling that functions, then it or one of its dependencies has TLA, in which case we panic.
Since a panic like "TLA is not allowed" would be hard to debug, …
=> fix(realms): Make realm creation not hang with async ops running

Cargo.lock, ops/Cargo.toml, ops/op2/dispatch_slow.rs
Fixes #98
If v8 fails to link, the proc macro won't compile, causing docs.rs to barf.
=> fix(core): don't include a v8 dependency as this breaks docs.rs

core/runtime/jsruntime.rs
This fixes regressions reported in https://github.com/denoland/deno/issues/19903.
We mistakenly were not waking up the event loop again if ops made progress
and there are pending dynamic imports waiting for TLA to resolve.
=> fix: run js event loop tick before polling dynamic imports

core/error.rs, core/runtime/bindings.rs, core/runtime/tests/misc.rs
Will fix ... https://github.com/denoland/deno/issues/20034.
As we know, `msg.get_stack_frames()` does not get populated properly for async op errors. That's why we use the 'call sites' passed to `prepareStackTrace()` as a source of truth instead. I had forgotten to account for that in one odd place.
=> fix: use call sites when checking for empty frames

core/runtime/jsruntime.rs, core/runtime/tests/snapshot.rs
Unblocks https://github.com/denoland/deno/pull/20082.
Fixes three tangled issues:
- `JsRuntime::poll_value(promise)` swallows non-awaited rejections returned from `poll_event_loop()` when `promise` is already settled.
- `JsRuntime::poll_value(promise)` runs the event loop once even if `promise` is already settled.
- `JsRuntime::call_and_await()` needs to explicitly call `check_promise_rejections()` at the end.
Some test expectations might need to add `(in promise)` to error strings. These are correct. There's at least one in CLI repo:
```diff
diff --git a/cli/tests/testdata/node/test.out b/cli/tests/testdata/node/test.out
index 8b7f0780f..3c54a15e8 100644
--- a/cli/tests/testdata/node/test.out
+++ b/cli/tests/testdata/node/test.out
@@ -147,7 +147,7 @@ error: Error: rejected from reject …
```
=> fix: don't swallow rejections in poll_value()

core/ops.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, ops/lib.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/async/async_arg_return_result.out, ops/op2/test_cases/async/async_opstate.out, ops/op2/test_cases/async/async_result.out, ops/op2/test_cases/async/async_result_impl.out, ops/op2/test_cases/async/async_result_smi.out, ops/op2/test_cases/sync/bool_result.out, ops/op2/test_cases/sync/result_primitive.out, ops/op2/test_cases/sync/result_scope.out, ops/op2/test_cases/sync/result_void.out, ops/optimizer_tests/incompatible_1.out, ops/optimizer_tests/op_blob_revoke_object_url.out, ops/optimizer_tests/op_print.out, ops/optimizer_tests/op_state_result.out, ops/optimizer_tests/op_state_warning.out, ops/optimizer_tests/opstate_with_arity.out, ops/optimizer_tests/option_arg.out, ops/optimizer_tests/param_mut_binding_warning.out, ops/optimizer_tests/strings_result.out, ops/optimizer_tests/u64_result.out, ops/optimizer_tests/unit_result.out, ops/optimizer_tests/unit_result2.out
Closes #51. `cargo test error` works in main repo.
=> refactor: move get_error_class_fn to OpCtx

.github/workflows/ci.yml, core/buffer_strategy.rs, core/io.rs, core/lib.rs, core/ops_builtin.rs, serde_v8/magic/v8slice.rs
With this PR, we no longer allow `BufMutView` or `BufView` to be backed by `Vec` (except in the case of a `bytes::Bytes`-backed `BufView` which could handle it internally). This allows us to add the `split_off` and `split_to` methods to `V8Slice` and our `Buf*View` buffers, which means that we can take subsets of existing V8 or Rust buffers.
Note that our mutable buffers are not cheaply cloneable, but we do allow for cheap splitting which allows for a buffer to be segmented into a cloneable read-only segment and a non-cloneable read-write segment.
This is required for us to handle channels that receive buffers from JavaScript, as internal buffering limits may require us to split those V8-backed arraybuffers to fit within other internal buffers (ie: calling read(1024) with a source that is …
=> feat(core): Add split_* methods to BufView and V8Slice

core/resources.rs
This will allow us to remove some `cfg` structures from `deno`.
=> feat(core): add is_terminal to ResourceHandle

core/runtime/ops.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs
This was unimplemented for async function return values
=> feat(ops): support #[serde] return from async ops

Cargo.toml
Change the repository from `denoland/deno` to `denoland/deno_core` to fix the
information shown by https://crates.io/crates/deno_core
BTW is there a reason why Deno crates don't publish their API docs to https://docs.rs/?
=> fix: repository URL in Cargo.toml

core/runtime/ops.rs, core/runtime/ops_rust_to_v8.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/op2/test_cases/async/async_result_smi.out, ops/op2/test_cases/sync/smi.out
`#[smi]`-tagged arguments were going through the wrong path because I neglected to restore the custom `Numeric(__SMI__)` handling in  #165.
To fix this, we use a `RustToV8Marker` to override the default behaviour and ensure that SMIs are always serialized as v8 i32s. Fixes a Deno crash in the HTTP test.
=> fix(ops): Handle #[smi] types

core/resources.rs
Follow-up to #179 -- we don't want to use this method.
=> chore(core): deprecate ResourceTable::close

Cargo.lock, Cargo.toml, core/Cargo.toml, ops/Cargo.toml, ops/op2/test_cases/async/async_arg_return.out, ops/op2/test_cases/async/async_arg_return_result.out, ops/op2/test_cases/async/async_jsbuffer.out, ops/op2/test_cases/async/async_opstate.out, ops/op2/test_cases/async/async_result.out, ops/op2/test_cases/async/async_result_impl.out, ops/op2/test_cases/async/async_result_smi.out, ops/op2/test_cases/async/async_v8_global.out, ops/op2/test_cases/async/async_void.out, ops/optimizer_tests/f64_slice.out, ops/optimizer_tests/op_ffi_ptr_value.out, ops/optimizer_tests/op_state_with_transforms.out, ops/optimizer_tests/raw_ptr.out, ops/optimizer_tests/uint8array.out, serde_v8/Cargo.toml
All deps are now workspace deps
Run a big cargo update
Required a reformat of proc_macro outputs due to a bump in prettyplease
=> chore: update Cargo.toml + Cargo.lock

core/01_core.js, core/02_error.js, core/examples/ts_module_loader.rs, core/runtime/tests/misc.rs
Also always enables `Error.prepareStackTrace` so that users of
`deno_core` don't need to set it up themselves.
=> chore: enable source map handling for TS example

ops/op2/signature.rs
We don't really support or test the fully-prefixed versions of imports, so let's provide a better error on these to suggest a fix rather than fail.
=> fix: disallow deno_core prefixes for most types

core/runtime/ops.rs, ops/lib.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/sync/op_state_attr.out, ops/op2/test_cases/sync/op_state_attr.rs, ops/op2/test_cases/sync/op_state_ref.out, ops/op2/test_cases/sync/op_state_ref.rs, ops/optimizer_tests/op_blob_revoke_object_url.out, ops/optimizer_tests/op_print.out, ops/optimizer_tests/op_state.out, ops/optimizer_tests/op_state_basic1.out, ops/optimizer_tests/op_state_generics.out, ops/optimizer_tests/op_state_result.out, ops/optimizer_tests/op_state_warning.out, ops/optimizer_tests/op_state_with_transforms.out, ops/optimizer_tests/opstate_with_arity.out, ops/optimizer_tests/option_arg.out, ops/optimizer_tests/param_mut_binding_warning.out, ops/optimizer_tests/raw_ptr.out, ops/optimizer_tests/u64_result.out, ops/optimizer_tests/unit_result.out, ops/optimizer_tests/unit_result2.out
If a user imports the common `std::borrow::Borrow` or `std::borrow::BorrowMut` traits, `op2` tends to behave badly. Any method that looks like one of these should be fully-qualified.
=> fix(ops): use explicit RefCell borrow/borrow_mut

core/01_core.js, core/ops_builtin.rs, core/ops_builtin_v8.rs, core/runtime/tests/ops.rs, core/source_map.rs
This function returns the first call site in the current stack that is
"user" code, i.e. has a file name starting with neither `ext:` or
`node:`.
=> feat: add core.currentUserCallSite()

core/runtime/jsruntime.rs, core/runtime/tests/jsrealm.rs
This is needed in order to implement `Deno.metrics()` equivalent in Rust.
=> feat: add JsRuntime::op_names

core/runtime/ops.rs, core/runtime/ops_rust_to_v8.rs
This matches the behaviour of the Fast API path.
Constructing v8:Externals with null pointers is undefined behaviour and may cause problems once pointer compression is turned on.
Closes #235
=> fix(ops): roundtrip external null pointers as JS null

core/runtime/ops.rs
=> fix(ops): returning computed null from `ptr::offset` in release mode is broken

core/ops_builtin_v8.rs, core/runtime/tests/mod.rs, core/runtime/tests/serialize_deserialize_test.js
This PR fixes `op_deserialize` when multiple array buffers are transferred.
fixes  https://github.com/denoland/deno/issues/20727
=> fix(ops): correctly handle multiple array buffers in op_deserialize

core/runtime/ops.rs
Trying to fix WPT for WS which construct `Uint8Array` with byte offset of 2 and length 8;
and expect a Uint8Array of length 6 to be returned.
=> fix: op2 #[anybuffer] byte offset

core/01_core.js, core/runtime/jsruntime.rs
Upto 2x faster encode/decode
```
divy@mini ~/g/deno (main)> deno run -A bench.js
decode: Hello 😃
cpu: unknown
runtime: deno 1.36.4 (aarch64-apple-darwin)
benchmark      time (avg)             (min … max)    
--------------------------------------------------
122.27 ns/iter  (122.02 ns … 215.82 ns)  
divy@mini ~/g/deno (main)> target/release/deno run -A bench.js
decode: Hello 😃
cpu: unknown
runtime: deno 1.36.4 (aarch64-apple-darwin)
benchmark      time (avg)             (min … max)       
---------------------------------------------------
64.02 ns/iter  (62.81 ns … 139.55 ns) 
```
=> perf: use V8 Deno builtins

core/inspector.rs
Needed for HMR functionality that needs to drive V8 inspector session progress.
=> chore: Make "LocalInspectorSession::receive_from_v8_session" public

ops/op2/signature.rs, ops/op2/signature_retval.rs
This was causing ops with `Result<X, Y,>` to fail to parse. `cargo fmt` likes to insert trailing commas for really long types, so this may get triggered occasionally.
=> fix(ops): Allow trailing comma for all generic types in parser

core/flags.rs
We experienced some weird V8 segfault by not adding a fake first argument as done in https://github.com/denoland/deno/blob/v1.37/cli/util/v8.rs
There's also a note about it in the documentation of `V8::set_flags_from_command_line`, which I copied here.
=> Tweak documentation of v8_set_flags

core/runtime/bindings.rs, core/runtime/jsruntime.rs, core/runtime/snapshot_util.rs, core/runtime/tests/jsrealm.rs
`register_ops: false` is a dangerous default and probably a footgun, so let's invert this and call it `skip_op_registration`.
=> feat(core): invert register_ops

core/external.rs
- Fix the type of macro argument (was `ident` but should be `ty`)
- Tweak how we get the address of the static to be slightly less unsafe (not really an issue, miri didn't complain just saw it)
- Use the correct type for external usage (no external package -- just deno_core crate root)
=> fix(core): use correct external package and fix external macro type

core/01_core.js, core/benches/ops/async.rs, core/benches/ops/async_harness.js, core/lib.rs, core/rebuild_async_stubs.js, core/runtime/tests/ops.rs
Adds a new template system for op async dispatch generation, and starts generating opAsync from it as well so we can play with performance more easily.
First pass at optimization: 5% improvement in async dispatch by avoiding allocation of promise IDs and generally doing less work in the async handlers.
Before:
```
test bench_op_async_void                  ... bench:      80,853 ns/iter (+/- 2,123)
```
After:
```
test bench_op_async_void                  ... bench:      76,799 ns/iter (+/- 1,158)
```
=> feat(core): speedier async stubs + template opAsync

core/lib.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/bindings.rs, core/runtime/jsruntime.rs
Closes https://github.com/denoland/deno_core/issues/326
This commit adds `RuntimeOptions.validate_import_attributes_cb` that can be
used to customize which import attributes are allowed.
=> feat: Import attributes validation callback

core/Cargo.toml, core/runtime/jsruntime.rs
Embedding ICU data into Deno binary is undesirable when linking with system-provided ICU (in Linux distributions) - it adds 10 MiB of unnecessary bloat.
This patch is already used in deno package for Alpine Linux.
=> build(core): add feature flag include_icu_data

core/modules/map.rs, core/modules/mod.rs, core/runtime/tests/snapshot.rs
`ModuleMap` now supports any type of module assertion (including arbitrary strings), however this has not been threaded through beyond this code.
=> feat(core): add support for other assertion types to ModuleMap

core/runtime/jsruntime.rs
Closes https://github.com/denoland/deno_core/issues/338
This implements a new function `call_with_args_and_await` on `JsRuntime` that allows users to call a JS function from the Rust runtime with args (unlike `call_and_await`).
=> feat(core): add function to call a JS function with args

core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/bindings.rs, core/runtime/jsruntime.rs
This commits adds "RuntimeOptions::import_meta_resolve_callback" option
that allows to customize behavior of `import.meta.resolve` API.
Required for https://github.com/denoland/deno/issues/21298.
=> feat: Add RuntimeOptions::import_meta_resolve_callback

Cargo.lock, Cargo.toml, core/Cargo.toml, core/lib.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/tests/misc.rs, core/tasks.rs
Provides an `OpState`-stored (for now) `V8TaskSpawner` and `V8CrossThreadTaskSpawner` that allow for submission of v8 tasks to a queue that is run alongside ops.
```
let task_spawner: &V8TaskSpawn = op_state.borrow();
task_spawner.spawn(|scope| {
/* use scope */
});
```
This allows you submit jobs into a queue that's run just before op dispatch (timing TBD and subject to change). The task is given a scope for the current context, and may do whatever it wishes.
This will likely turn into microtask submission API in the future.
=> feat: V8TaskSpawner

core/examples/fs_module_loader.rs, core/examples/op2.rs, core/examples/schedule_task.rs, core/examples/ts_module_loader.rs, core/modules/tests.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, core/runtime/tests/error.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs, core/runtime/tests/ops.rs, core/runtime/tests/snapshot.rs, testing/checkin/runner/mod.rs
This commit removes "old" event loop polling methods in favor
of "new" ones - now all methods for polling the event loop require
explicit "PollEventLoopOptions" option instead of accepting
a single bool.
=> refactor: Change signatures of JsRuntime event loop methods

core/runtime/jsruntime.rs
This commit adds "RuntimeOptions::wait_for_inspector_disconnect_callback"
that allows to pass a callback that will be called when the event loop runs out of
work, but there are active, non-blocking inspector sessions - that is sessions
from "Chrome DevTools". This allows to print a message notifying user that
the program has finished, but is waiting for DevTools to disconnect to exit
the process.
PR in `deno`: https://github.com/denoland/deno/pull/21633
=> feat: Add RuntimeOptions::wait_for_inspector_disconnect_callback

serde_v8/magic/external_pointer.rs
Also mark ExternalPointer as repr(transparent).
=> feat(serde_v8): From ExternalPointer to *mut and *const c_void

core/01_core.js, core/ops_builtin.rs
In preparation for https://github.com/denoland/deno_core/issues/223, start ensuring exclusive imports of ops in modules.
We have a fair bit of work to migrate ops to ensureFastOps which is similar in style to the eventual op import design that it will be the majority of the work.
=> feat(core): remove ops from core.ops when using ensureFastOps

ops/op2/README.md, ops/op2/dispatch_fast.rs, ops/op2/test_cases/sync/bool_result.out, ops/op2/test_cases/sync/result_external.out, ops/op2/test_cases/sync/result_primitive.out, ops/op2/test_cases/sync/result_void.out, ops/op2/test_cases/sync/result_void.rs
```rs
// compiles
#[op2]
pub fn op_slow_anyhow_result(_: &mut v8::HandleScope) -> anyhow::Result<()> {
Ok(())
}
// compiles
#[op2(fast)]
pub fn op_fast_anyhow_result() -> anyhow::Result<()> {
Ok(())
}
// compiles
#[op2]
pub fn op_slow_std_io_result(_: &mut v8::HandleScope) -> std::io::Result<()> {
Ok(())
}
// does not compile (fixed by this PR)
#[op2(fast)]
pub fn op_fast_std_io_result() -> std::io::Result<()> {
Ok(())
}
```
=> fix(ops): support returning non-`anyhow` `Result` from fast sync op

core/feature_checker.rs
I need this for https://github.com/denoland/deno/pull/21452
=> fix: pass api_name to FeatureChecker::warn_cb

ops/op2/dispatch_fast.rs, serde_v8/magic/v8slice.rs, testing/checkin.d.ts, testing/checkin/runner/mod.rs, testing/checkin/runner/ops_buffer.rs, testing/checkin/runner/testing.rs, testing/lib.rs, testing/unit/ops_buffer_test.ts
We should always clamp the expected buffer range to that of the underlying storage.
=>  fix(core): clamp V8Slice slice to bounds 

Cargo.lock, Cargo.toml, core/runtime/jsruntime.rs
This reverts commit 492ffd836e930c237817c9b9a4fbc410570bff86.
This update started causing problems in globals handling in "deno".
=> Revert "Upgrade rusty_v8 to 0.83.0 (#424)"

core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/jsruntime.rs
This commit adds "JsRuntime::custom_module_evaluation_cb" as well as "ModuleType::Other"
that allow embedders to customize and support more module types (like WASM, test or bytes).
If no callback is provided and a "ModuleType::Other" is loaded then an error is returned.
Ref https://github.com/denoland/deno_core/pull/402.
=> feat: Add JsRuntime::custom_module_evaluation_cb to support arbitrary module types

core/modules/map.rs, core/modules/mod.rs, core/runtime/jsrealm.rs
This commit adds "ModuleMap::new_module_from_js_source" method.
This method is pretty much the same as "ModuleMap::new_es_module", but allows to customize the 
type of the module - ie. it allows to create a module from JS source with any type - this allows for "shim"
modules. One might create a JS "shim" that acts as a proxy to a WASM module.
A drive by cleanup of "ModuleError" was done as well.
Ref https://github.com/denoland/deno_core/pull/402
=> refactor: Add ModuleMap::new_module_from_js_source

core/examples/ts_module_loader.rs, core/lib.rs, core/modules/loaders.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/recursive_load.rs, core/modules/tests.rs, testing/checkin/runner/ts_module_loader.rs
This commit adds additional argument to "ModuleLoader::load" method that
is "RequestedModuleType". This argument can be used by the embedder to 
decide if the loaded module should be refused (eg. trying to load a module
with type "json", but the actual MIME type is not "application/json").
In a follow up I might extract `is_dyn_import` and `requested_module_type`
into a helper struct (maybe `LoadMetadata`).
Ref https://github.com/denoland/deno_core/pull/402
=> feat: add 'requested_module_type' to ModuleLoader::load

core/lib.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs
This commit changes "CustomModuleEvaluationCb" to return an enum
that tells how to interpret the return value.
In addition to evaluating the returned value as a synthetic module like before
(using "CustomModuleEvaluationKind::Synthetic"), now users can evaluate a
synthetic module and a "computed" module that uses the synthetic module
(using "CustomModuleEvaluationKind::ComputedAndSynthetic").
Ref https://github.com/denoland/deno_core/pull/402
=> feat: Change CustomModuleEvaluationCb to return an enum

core/examples/fs_module_loader.rs, core/modules/loaders.rs
A little cleanup and showcase how to wire up custom
module types in the `fs_module_loader.rs` example.
Ref #402
=> feat(example): add 'text' and 'bytes' imports to fs_module_loader.rs

core/runtime/jsruntime.rs, core/runtime/tests/misc.rs
Fix related to https://github.com/denoland/deno_core/issues/450.
After PR https://github.com/denoland/deno_core/pull/359, `run_event_loop()` stopped returning error `"Uncaught Error: execution terminated"` after `terminate_execution()` is called, instead it returns `Ok(())`.
As [is_execution_terminating()](https://docs.rs/v8/0.82.0/v8/struct.Isolate.html#method.is_execution_terminating) is not flagging the termination after `run_event_loop()` returns, it is not possible to detect the termination and act on it.
This PR restores the previous behavior.
=> fix: return "Uncaught Error" on terminate_execution() during run_event_loop

core/modules/map.rs, core/modules/module_map_data.rs
Prerequisite for "virtual ops modules".
This allows to create synthetic modules with multiple
exports. Previously only "default" export was supported,
which was fine for JSON modules and custom evaluated
modules, but lacks flexibility needed to generate modules
for ops in an extension.
=> feat: Allow synthetic modules to provide multiple exports

core/extensions.rs, core/external.rs, core/fast_string.rs, core/lib.rs, core/resources.rs
Current macros are not hygienic in path resolution. This causes compile error with codes like below.
```rust
deno_core::extension!(
ext,
js = [ "/path/to/ext.js" ]
);
mod std {}
```
error diagnostic:
```
error[E0433]: failed to resolve: could not find `borrow` in `std`
--> src/lib.rs:14:1
|
14 | / deno_core::extension!(
15 | |     ext,
16 | |     js = [ "/path/to/ext.js" ],
17 | | );
| |_^ could not find `borrow` in `std`
|
= note: this error originates in the macro `deno_core::extension` (in Nightly builds, run with -Z macro-backtrace for more info)
```
This PR almost resolves this problem, by using unambiguous paths. There are still ambiguous paths remaining, but they won't couse such a issue because they only appear in unexported macros. I'm sorry if I missed something :pray: …
=> Reduce ambiguous paths in macros

core/extensions.rs, core/runtime/bindings.rs, core/runtime/tests/ops.rs
This commit changes what "disabling" an op means. Before a disabled op
was never registered. This posed some challenges, especially as we
trying to provide "virtual ops modules" (https://github.com/denoland/deno_core/issues/223),
having ops conditionally available makes it super hard to properly
snapshot and set up the runtime.
With this change, "disabling" an op makes it throw when called.
Closes https://github.com/denoland/deno_core/issues/447
=> feat: Disabling an op replaces it with a function that throws

core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/op_driver/erased_future.rs, core/runtime/op_driver/future_arena.rs, core/runtime/op_driver/futures_unordered_driver.rs, core/runtime/op_driver/joinset_driver.rs, core/runtime/op_driver/mod.rs, core/runtime/op_driver/op_results.rs
This is the underlying infrastructure we need to get the op sanitizer working in Rust. There are no useful public-facing APIs from this yet, but it implements the op portion of the work.
Step 2 will be adding resources and timers to the API, then we'll be able to implement this in Deno itself.
=> feat: Infrastructure for op sanitizer in deno_core

.cargo/config.toml, .github/workflows/ci-job.yml, .github/workflows/ci-nop/action.yml, .github/workflows/ci-publish/action.yml, .github/workflows/ci-test-publish/action.yml, .github/workflows/ci.yml, serde_v8/utilities/Cargo.toml, tools/deno_core_workspace.ts, tools/publish_dry_run.ts
Changes to publishing/build workflows:
- No longer build twice when running a version bump. The only branch that will trigger a build will be `main`.
- Tag builds run an empty matrix, since they are being built from a main commit that should succeed, and the publish workflow runs a test compile on top of everything.
- Even if the tag build failed with an error, we still just went ahead and published that tag!
- All PRs run a `cargo publish` dry-run against a test server
=> chore: improve publish dry-run

core/01_core.js
I need this to cleanup deprecated `rid` properties in Deno.
=> Add Deno.core.internalRidSymbol

core/examples/ts_module_loader.rs, core/lib.rs, core/modules/loaders.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/recursive_load.rs, core/modules/tests.rs, testing/checkin/runner/ts_module_loader.rs
Checking if having this enum is beneficial and can help optimize some of the code.
In many situation embedders will rely on `ModuleLoader::prepare_module_load` 
and assemble the whole graph themselves. Then when actually loading modules,
they will wrap the already ready value into an empty future that needs to be boxed.
=> feat: Add ModuleLoadResponse

core/cppgc.rs, core/runtime/ops.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/cppgc_resource.rs
Builtin support for getting a reference to a `CppGcObject<T>`.
```rust
#[op2(fast)]
fn op_file(#[cppgc] file: &std::fs::File) {}
```
=> feat(ops): add `#[cppgc]` argument attribute

core/runtime/bindings.rs
Calling `v8::ExternalReferences::new` does not take ownership of the Vec - it internally copies the values into a new Vec. As a result, the memory owned by the original Vec was never getting freed.
=> fix: Remove 'leak' call when creating `v8::ExternalReferences`

core/cppgc.rs, core/runtime/jsruntime.rs, testing/checkin/runner/mod.rs, testing/checkin/runner/ops.rs, testing/checkin/runner/ops_worker.rs, testing/checkin/runner/testing.rs, testing/checkin/runtime/__init.js, testing/checkin/runtime/worker.ts, testing/integration/error_async_stack/error_async_stack.out, testing/integration/worker_spawn/worker.ts, testing/integration/worker_spawn/worker_spawn.out, testing/integration/worker_spawn/worker_spawn.ts, testing/integration/worker_terminate/worker.ts, testing/integration/worker_terminate/worker_terminate.out, testing/integration/worker_terminate/worker_terminate.ts, testing/lib.rs, testing/tsconfig.json
We can spawn a worker and send messages to it (and it can send messages back), and terminate it.
=> feat(testing): Add a worker subsystem to checkin

core/Cargo.toml, core/main.rs
This commit adds minimal binary target to "deno_core" crate.
It is now possible to "cargo run ./path/to/file.ts" to execute a file.
This feature is being added for development and testing purposes only
and is not meant for end-users. The API is minimal and the binary can't
do anything interesting.
"fs_module_loader" example has been removed in favor of binary target.
Closes https://github.com/denoland/deno_core/issues/412
Once #415 lands we can extend functionality further.
=> feat: Add `dcore` bin target

core/01_core.js, core/lib.deno_core.d.ts, core/modules/tests.rs
These are common utilities that are duplicated several times in `deno` and Deploy.
=> feat: Add property definition utilities to Deno.core

core/runtime/bindings.rs, core/runtime/jsruntime.rs
=> refactor: make static strings use easier

core/lib.rs, core/main.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/bindings.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs
This commit adds "CustomModuleEvaluationCtx" struct that is passed to
"CustomModuleEvaluationCb" and allows to analyze contents of WASM modules.
Specifically we add the ability to analyze imports and exports of WASM modules
that can be used to build up support for WASM imports.
=> feat: Add bindings to analyse WASM modules

core/extensions.rs, core/lib.rs
Removes `ExtensionBuilder` which has been unsupported and untested for almost a year. Also removes `init_js_only` which has been deprecated for nearly as long.
=> chore(core): remove ExtensionBuilder

core/extensions.rs, core/runtime/bindings.rs, core/runtime/jsruntime.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs, core/runtime/tests/snapshot.rs, testing/checkin/runner/mod.rs
This looks pretty big, but it's mostly a cleanup of `include_js_files!` that makes it easier to understand and easier to maintain moving forward.
`include_js_files!` supports four styles of includes:
- `"file"` <- old
- `"file" with_specifier "specifier"` <- old, triggers a deprecation warning with a hint
- `specifier = "file"` <- new
- `specifier = { source = "source" }` <- new, see below
The `specifier = "file"` syntax will be preferred to replace the current `"file" with_specifier "specifier"` syntax, but won't be removed yet. If we want to add any other possible options to this macro, it's just too hard to expand the old syntax (which is why I introduced this new syntax!).
We now support an inline, embeddable string script for all places where `include_js_files!` is used:
``` …
```
=>  refactor(core): clean up include_js_files! macros 

core/modules/map.rs, core/modules/mod.rs, core/modules/module_map_data.rs, core/modules/tests.rs, core/runtime/bindings.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/tests/snapshot.rs
This commit prepares for support of WASM modules.
A new variant of "ModuleType::Wasm" was added.
Actually trying to load a WASM module will throw an error.
=> refactor: Prepare for Wasm imports support

core/00_infra.js, core/lib.deno_core.d.ts, testing/checkin/runtime/async.ts, testing/unit/ops_async_test.ts
This tweaks the opcall tracing interface to make it compatible with a Rust implementation in the future, as well as adding some basic testing for it.
=> refactor(core): Add tests to opcall tracing so we can make changes

core/02_error.js
Working on https://github.com/denoland/deno/pull/22273 I found that we can't remove
`op_format_file_name`, `op_apply_source_map` and `op_apply_source_map_filename`
from `Deno.core.ops`, because they are used in `02_error.js`.
=> refactor: destructure ops in 02_error.js

core/01_core.js, core/lib.deno_core.d.ts, core/ops_builtin.rs
This is a common utility used in `ext/fs` and `ext/net` in `deno` repo.
It's weirdly created in `ext/web` so it can be shared between the two extensions.
=> feat: Add `Deno.core.createCancelHandle()`

Cargo.lock, Cargo.toml, core/Cargo.toml, core/fast_string.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/module_map_data.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs, core/runtime/snapshot_util.rs, serde_v8/magic/value.rs
This code will be used for the future opcall tracing work, as we need to get a reference to a number of primordials on the Rust side and persist those references in the snapshot.
This drastically simplifies our management of snapshot sidecar data. 
As a positive side-effect, the management of module map data becomes trivially easy. In the future, we may decide to serialize that serde_v8 data using a more efficient protocol, but that's left as a future task.
The sidecar data is serialized in the snapshot by using a single, nested serde_v8 struct and a collection of `v8::Data` objects that are referenced by ID. Because we cannot use serde_v8 for `v8::Data` objects like `v8::Module`, these are simply aggregated and stored in successive indexes of the snapshot per-context data.
It's a shame …
=> feat: Use serde_json and Snapshot*DataStore for managing snapshot sidecar data

core/00_infra.js, core/01_core.js, core/ops_builtin.rs, core/ops_builtin_v8.rs, core/rebuild_async_stubs.js, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, testing/unit/ops_async_test.ts
Moves the core of the opcall tracing functionality into Rust. Tested against deno (which will need small source changes).
Re-organizes the op dispatch code a bit as well, but performance is unimpacted per benchmarks (if not slightly faster).
=> refactor(core): opcall tracing in Rust

Cargo.lock, Cargo.toml, core/modules/map.rs, testing/unit/tc39_test.ts
This reverts commit 312cf8e0f668325605cf35900e8c8486a34ebda4.
This V8 upgrade causes some serious test failures in Deno: 
https://github.com/denoland/deno/actions/runs/7981611991/job/21793650383?pr=22505
This will require more work. I don't want to block others before the Deno v1.41 release.
=> Revert "chore: update rusty_v8 to 0.84.0 (#587)"

core/main.rs, core/runtime/bindings.rs, core/runtime/jsruntime.rs
This commit changes internal JS source code of "deno_core"
to be included in the binary. We now use "v8::OneByteConst" and
pass external references to the sources which allows V8 to take
an optimized path when deserializing the snapshot. Local tests
with flamegraphs confirm that it's now cheaper to deserialize the
snapshot.
Closes https://github.com/denoland/deno_core/issues/589
=> refactor: Use v8::OneByteConst for internals scripts

core/web_timeout.rs
This was previously implemented in Deno, but we want it to work here in WebTimers implementation.
To enable more comprehensive testing, #[cfg(test)] will do everything except call the WinMM APIs required to set the timer period. These APIs are imported directly to avoid adding an extra dep.
=> feat(core): Implement high-res timer lock

.github/workflows/ci-lint/action.yml, tools/check.ts, tools/format.ts, tools/lint.ts
Usage:
- `tools/check.ts lint`: runs a lint and reports errors
- `tools/check.ts lint --fix`: attempts to fix lint problems
- `tools/check.ts format`: formats the codebase
- `tools/check.ts format --check`: checks if the codebase is formatted, fails if not
=> chore: add a tools/check.ts for lint and format

core/benches/ops/async.rs, core/benches/ops/sync.rs, core/examples/disable_ops.rs, core/examples/eval_js_value.rs, core/examples/hello_world.rs, core/fast_string.rs, core/modules/tests.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, core/runtime/snapshot.rs, core/runtime/tests/error.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs, core/runtime/tests/mod.rs, core/runtime/tests/ops.rs, core/runtime/tests/snapshot.rs
Split out from #620 
We can simplify this embedder-facing API by using a single overload. This reduces the noise of the other PR significantly.
=> refactor(core): execute_script_static -> execute_script

Cargo.lock, Cargo.toml, core/examples/ts_module_loader.rs, core/modules/loaders.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs, core/ops_builtin_v8.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/tests/misc.rs, testing/checkin/runner/ts_module_loader.rs
This PR adds V8 code cache support for ES modules loaded through `ModuleLoader`, and for scripts evaluated through `evalContext` (used by `require` in Deno). Embedders have full control over whether code caching is enabled, and how code cache is retrieved/stored.
=> feat: support for v8 code cache

core/modules/loaders.rs, core/modules/tests.rs, testing/checkin/runtime/__init.js
Before
```ts
// In `ext/node/polyfills/foo.ts`
import * as errors from "ext:deno_node/internal/errors.ts";
```
Now
```ts
// In `ext/node/polyfills/foo.ts`
import * as errors from "./internal/errors.ts";
```
It's pretty ugly because the `url` crate restricts you from directly modifying "bases" or "hosts" of URLs that aren't valid bases, but this avoids having to reimplement a worse version of `Url::join`
=> Allow relative imports in extension JS/TS code

core/01_core.js, core/benches/ops/async_harness.js, core/benches/ops/sync_harness.js, core/lib.deno_core.d.ts, core/runtime/ops.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs, core/runtime/tests/ops.rs, testing/checkin/runtime/async.ts, testing/unit/ops_buffer_test.ts, testing/unit/resource_test.ts, testing/unit/stats_test.ts
Instead embedders should tear off appropriate ops
directly from `Deno.core.ops` object.
This API just added another layer of indirection for no obvious
reason.
Ref https://github.com/denoland/deno_core/issues/521
=> refactor: Remove Deno.core.ensureFastOps

core/ops.rs, core/runtime/jsruntime.rs
=> fix: Add public method to JsRuntime to get op metadata by name

Cargo.lock, Cargo.toml, core/Cargo.toml, core/gotham_state.rs, core/modules/map.rs, core/runtime/bindings.rs, core/runtime/tests/ops.rs
We have not used these logs in the past 2-3 years, it's questionable to keep them around.
=> refactor: remove log crate

core/runtime/ops.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/cppgc_resource.rs, testing/checkin/runner/mod.rs, testing/checkin/runner/ops_async.rs, testing/unit/resource_test.ts
`#[cppgc]` return values were added in https://github.com/denoland/deno_core/commit/a736d868d091406ee20c3fda44bde56def2e73f3 which made 
creation of cppgc backed objects possible without direct access to V8 APIs. 
This patch builds on top of that and adds `#[cppgc]` support for async ops.
=> feat(op2): support cppgc in async ops

ops/op2/dispatch_fast.rs, ops/op2/test_cases/async/async_deferred.out, ops/op2/test_cases/async/async_lazy.out, ops/op2/test_cases/sync/add.out, ops/op2/test_cases/sync/bigint.out, ops/op2/test_cases/sync/bool.out, ops/op2/test_cases/sync/bool_result.out, ops/op2/test_cases/sync/buffers.out, ops/op2/test_cases/sync/buffers_copy.out, ops/op2/test_cases/sync/cfg.out, ops/op2/test_cases/sync/clippy_allow.out, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/doc_comment.out, ops/op2/test_cases/sync/fast_alternative.out, ops/op2/test_cases/sync/generics.out, ops/op2/test_cases/sync/op_state_attr.out, ops/op2/test_cases/sync/op_state_rc.out, ops/op2/test_cases/sync/op_state_ref.out, ops/op2/test_cases/sync/result_external.out, ops/op2/test_cases/sync/result_primitive.out, ops/op2/test_cases/sync/result_void.out, ops/op2/test_cases/sync/smi.out, ops/op2/test_cases/sync/string_cow.out, ops/op2/test_cases/sync/string_onebyte.out, ops/op2/test_cases/sync/string_owned.out, ops/op2/test_cases/sync/string_ref.out, ops/op2/test_cases/sync/v8_ref_option.out
before `#[op2(fast)]` would generate
```rust
fn v8_fn_ptr_fast(..) {
//
}
```
now
```rust
extern "C" fn v8_fn_ptr_fast(..) {
//
}
```
=> fix(op2): Mark "fast" op function pointers `extern "C"`

core/ops_builtin_v8.rs
Removes usages of `serde_v8::Value` in favor of manually handling `v8::Value` in:
- `op_leak_tracing_get_all`
- `op_get_promise_details`
- `op_get_proxy_details`
=> refactor: Remove usages of serde_v8::Value

core/ops.rs
We now explicitly call `drop_in_place` on the allocations, which will invoke the C++ '_DELETE' method in the latest `rusty_v8`
=> fix: Prevent  CFunctionInfo/CTypeInfo leak in OpCtx

core/runtime/setup.rs, testing/unit/tc39_test.ts
related: https://github.com/denoland/deno/issues/17944#issuecomment-2068131513, https://github.com/denoland/deno/issues/23450
Removed flags enabled by default and added flags for ~~Explicit Resource Management~~ and Float16Array.
=> feat: update v8 flags

core/runtime/jsruntime.rs, core/tasks.rs, testing/checkin/runner/mod.rs, testing/checkin/runner/ops_async.rs, testing/lib.rs, testing/unit/task_test.ts
Ref https://github.com/denoland/deno/issues/21686
If we had additional tasks generated while servicing these tasks we'd eventually fail to wake the waker (which no longer exists in the task spawner).
=> fix(core): don't lose waker for tasks

core/modules/map.rs, core/modules/mod.rs, core/modules/recursive_load.rs, core/modules/tests.rs, core/runtime/tests/snapshot.rs
Seems like it was needlessly going back and forth between a Url and String?
=> refactor: keep ModuleRequest.specifier as a Url

core/lib.rs, core/runtime/ops_rust_to_v8.rs, core/to_from_v8.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/from_v8.out, ops/op2/test_cases/sync/from_v8.rs, ops/op2/test_cases/sync/to_v8.out, ops/op2/test_cases/sync/to_v8.rs, serde_v8/error.rs, serde_v8/tests/de.rs
Adds support for
```rust
// calls `Foo`'s `ToV8` impl
#[op2]
#[to_v8]
fn op_foo() -> Foo {
todo!()
}
// calls `Bar`'s `FromV8` impl
#[op2]
fn op_bar(#[from_v8] bar: Bar) { }
```
=> Support ToV8/FromV8 in `#[op2]`

core/feature_checker.rs, core/lib.rs, core/modules/tests.rs, core/ops_builtin.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, core/runtime/snapshot.rs, core/runtime/tests/ops.rs, core/web_timeout.rs
Didn't catch anything, but these lint rules are useful imo.
=> chore: enable clippy::unused_async, print_stdout, and print_stderr

core/convert.rs, core/error.rs, core/lib.rs, core/runtime/ops.rs, core/to_from_v8.rs
Adds two wrapper structs which implement two different modes of serializing/deserializing numeric types:
```rust
pub struct Smi<T: SmallInt>(pub T);
// serializes like #[smi] (but without fast call support)
#[op2]
#[to_v8]
fn op_returns_smi() -> Smi<u32> {
Smi(1)
}
pub struct Number<T: Numeric>(pub T);
// serializes like #[number]
#[op2]
#[to_v8]
fn op_returns_number() -> Number<u64> {
Number(2)
}
```
Also adds an impl for `bool` itself, which is fairly uncontroversial I think.
TODO:
=> feat: Add `ToV8`/`FromV8` impls for bool and numeric types

Cargo.lock, core/async_cancel.rs, core/gotham_state.rs, core/web_timeout.rs, rust-toolchain.toml, serde_v8/magic/any_value.rs, serde_v8/magic/bigint.rs, serde_v8/magic/buffer.rs, serde_v8/magic/bytestring.rs, serde_v8/magic/detached_buffer.rs, serde_v8/magic/external_pointer.rs, serde_v8/magic/transl8.rs, serde_v8/magic/u16string.rs, serde_v8/magic/value.rs, serde_v8/ser.rs, testing/checkin/runner/testing.rs
We bump Rust to 1.78, but for the tests to pass we need to remove the UB that we've been relying on:
1. Opaque pointers no longer rely on values on the stack (!)
2. We no longer take a `&mut` from a u64 that comes from a `&` (UB)
3. ToV8Buffer gets a RefCell for proper interior mutability
Lots of sketchiness left in serde_v8 but hopefully this fixes the major fire.
serde_v8 is considered deprecated so we're likely not going to touch this code much more than this band-aid.
=> chore: bump Rust and cargo update

core/modules/map.rs, testing/integration/user_breaks_promise_constructor/user_breaks_promise_constructor.out, testing/integration/user_breaks_promise_constructor/user_breaks_promise_constructor.ts, testing/integration/user_breaks_promise_species/user_breaks_promise_species.out, testing/integration/user_breaks_promise_species/user_breaks_promise_species.ts, testing/lib.rs
Fixes: https://github.com/denoland/deno_core/issues/742
Fixes: https://github.com/denoland/deno_core/issues/743
`pending_mod_evaluation` is set before calling Module::Evaluate, and unset in the promise handlers for the promise returned by evaluate. If setting up those promise handlers fails for some reason, we can end up in a case where evaluation has finished but we haven't unset `pending_mod_evaluation`, which makes the core event loop assume that there is a pending stalled tla message, and it ends up panicking.
=> fix(core): don't crash when user breaks promise global

ARCHITECTURE.md
This is a first pass at `ARCHITECTURE.md`, a high-level overview of how `deno_core` works.
=> chore: ARCHITECTURE.md

Cargo.lock, Cargo.toml, core/Cargo.toml, core/lib.rs, core/modules/loaders.rs, core/modules/map.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/jsruntime.rs
This avoids the cli having to re-lookup the hash again.
=> refactor: pass hash into code cache

core/modules/mod.rs
Helper for getting the bytes from one of these.
=> feat: `ModuleSourceCode` - `as_bytes()`

core/runtime/jsruntime.rs
Added a new constructor variant that does not panic
Existing constructor can then simply take in the returned error and panic
=> Add non-panic constructor for runtimes

core/lib.rs, core/ops.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs
Allows an embedder to track "external" operations which should still keep the event loop alive. Will be used to ref napi threadsafe functions.
=> feat: ExternalOpsTracker

core/modules/map.rs, core/runtime/bindings.rs, testing/checkin/runner/extensions.rs, testing/checkin/runner/ops_async.rs, testing/checkin/runtime/async.ts, testing/integration/dyn_import_no_hang/dyn_import_no_hang.js, testing/integration/dyn_import_no_hang/dyn_import_no_hang.out, testing/integration/dyn_import_no_hang/dynamic.js, testing/lib.rs
Fixes a hang that could occur when a module contained a dynamic import that doesn't resolve immediately, and there was a pending op outstanding.
The original reproduction (ref  https://github.com/denoland/deno/issues/24098) effectively boiled down to this:
```ts
// main.ts
Deno.serve(async function (_req: Request): Promise<Response> {
await import("./repro.ts");
console.log("imported module");
return new Response("done");
});
// repro.ts
await new Promise<void>((resolve) => setTimeout(resolve, 0));
console.log("module executed");
```
Upon getting a request, it would hang when trying to import `"repro.ts"`. What was happening here was that `Deno.serve` created an op (`op_http_serve`) that stayed pending indefinitely, so we [assumed](https://github.com/denoland/deno_core/blob/4beb54e862805be …
=> fix: Wake event loop when dynamic import promise resolves

core/lib.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs
Remove usage of rusty_v8 annex slots for storing `ContextState` and `ModuleMap` and instead store them directly in a dedicated embedder field.
Needed for https://github.com/denoland/deno/pull/23976
=> store `ContextState` and `ModuleMap` in embedder slots

core/lib.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs
This reverts commit 98d52cf97c1574b3ae642b8b4745590d72da7d0c.
CC @littledivy I had trouble updating `deno_core` in Deno as it died on `node_unit_tests::vm_test`
with signal 11 during `vm context promise rejection` test. Also `Box<Rc<...>>` seems fishy as pointed
as by @dsherret in https://github.com/denoland/deno_core/pull/775#discussion_r1631733833
=> Revert "store `ContextState` and `ModuleMap` in embedder slots (#772)"

core/modules/map.rs, core/runtime/jsrealm.rs
During `JsRuntime` drop there were situations when `ModuleMap` was actually not
dropped. This could happen if there were pending futures stored in the `ModuleMap`.
These futures contain references to `ModuleMap`. The situation lead to memory being
leaked and subtle bugs in logic because the futures were not dropped either.
`ModuleMap::destroy()` was added that clear all pending futures and
other relevant data from the map during destruction of `JsRealm`.
=> fix: `ModuleMap` was not dropped if it had pending futures

Cargo.lock, Cargo.toml, core/lib.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs
Verified that `node::unit_vm` tests pass in Deno
=> Reland "store ContextState and ModuleMap in embedder slots"

core/cppgc.rs, core/lib.rs, core/ops.rs, core/runtime/ops.rs, core/runtime/ops_rust_to_v8.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/generator_state.rs, ops/op2/mod.rs, ops/op2/signature.rs, ops/op2/test_cases/async/async_cppgc.out, ops/op2/test_cases/async/async_cppgc.rs, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/cppgc_resource.rs, ops/op2/test_cases_fail/lifetimes.rs, ops/op2/test_cases_fail/lifetimes.stderr, testing/checkin/runner/ops.rs, testing/checkin/runner/ops_async.rs, testing/checkin/runner/ops_worker.rs
Optionals are supported both as arguments, via
`#[cppgc] resource: Option<&T>`, and as return
values, via `Option<T>`.
This commit also adds the `GcResource` trait,
which all CppGc resources must implement. This is
done to ensure that one does not accidentally
create CppGc objects for resources that one did
not intend to be managed by CppGc.
=> feat: add Option<GcResource> support in ops

core/cppgc.rs, core/runtime/ops.rs, ops/op2/dispatch_async.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/cppgc_resource.rs, ops/op2/test_cases_fail/lifetimes.rs, ops/op2/test_cases_fail/lifetimes.stderr
Allow `#[cppgc] _: &mut T` and `#[cppgc] _: Option<&mut T>`
Closes https://github.com/denoland/deno_core/issues/787
Trying to use it with async op gives a compiler error:
```
error[E0308]: mismatched types
--> core/runtime/ops.rs:1911:3
|
1911 |   #[op2(async)]
|   ^^^^^^^^^^^^^
|   |
|   types differ in mutability
|   arguments to this function are incorrect
|
= note: expected mutable reference `&mut TestResource`
found reference `&TestResource`
note: associated function defined here
--> core/runtime/ops.rs:1911:3
|
1911 |   #[op2(async)]
|   ^^^^^^^^^^^^^
1912 |   pub async fn op_test_set_cppgc_resource(#[cppgc] resource: &mut TestResource, value: u32) {
```
=> Allow `#[cppgc] &mut T` in sync ops

core/cppgc.rs, core/runtime/ops.rs, ops/op2/dispatch_async.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/cppgc_resource.rs, ops/op2/test_cases_fail/lifetimes.rs, ops/op2/test_cases_fail/lifetimes.stderr
Reverts denoland/deno_core#791
See https://github.com/denoland/deno_core/pull/791#pullrequestreview-2132050958
The following needs to be addressed before relanding:
1. Disallow multiple `&mut T` in the same op.
2. Make a `try_unwrap_cppgc_object` unsafe variant.
3. Disallow use in `op(reentrant)`
=> Revert "Allow `#[cppgc] &mut T` in sync ops"

Cargo.lock, Cargo.toml
Includes: 
- [feat: Add Source Maps APIs ](https://github.com/denoland/rusty_v8/commit/49b92c1e7602c2de900ede0e1b59cb97003899b8)
=> feat: upgrade rusty_v8 to 0.96.0

Cargo.lock, Cargo.toml, core/cppgc.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/async/async_cppgc.out, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases_fail/lifetimes.stderr
Uses https://github.com/denoland/rusty_v8/pull/1523 to avoid cppgc::Member overhead. Also move all Persistent logic into cppgc.rs to clean up the macro code.
There is done using a new `Ptr` struct which can deref into the inner member of `CppGcObject`. This is structured so as to play a little trick and inline `T` into `CppGcObject<T>` which halves the allocations and enables a future change for getting `&dyn Reference` from deno-managed cppgc objects.
=> feat: use cppgc::Ptr

core/fast_string.rs, core/runtime/bindings.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/op_driver/erased_future.rs, core/runtime/snapshot.rs, core/tasks.rs, rust-toolchain.toml, serde_v8/magic/value.rs
since i had to annotate all the `transmute`s for clippy i removed a few that were not needed.
=> rust 1.79.0

core/extension_set.rs, core/runtime/jsruntime.rs, core/source_map.rs
Splitting out a simplification from https://github.com/denoland/deno_core/pull/819.
=> refactor: Simplify SourceMapGetter and SourceMapper

core/examples/ts_module_loader.rs, core/lib.rs, core/modules/loaders.rs, core/runtime/jsruntime.rs, core/source_map.rs, testing/checkin/runner/mod.rs, testing/checkin/runner/ts_module_loader.rs
This commit deprecates `SourceMapGetter` trait, `JsRuntime::source_map_getter`
option and updates `ModuleLoader` trait to have the same methods as
`SourceMapGetter`.
In real usage it's always implementor of `ModuleLoader` that also implements
`SourceMapGetter`. It makes little sense to keep these two trait separate.
This will open up doors for native source map support that is being
developed in https://github.com/denoland/deno_core/pull/819.
`SourceMapGetter` is scheduled to be removed in 0.297.0.
=> feat: Depcrate `SourceMapGetter`, move methods to `ModuleLoader`

core/error.rs, core/source_map.rs
Fixes `SourceMapper` API that was changed in https://github.com/denoland/deno_core/pull/823.
Now the source lines are correctly mapped even if deprecated `SourceMapGetter` API is not
used.
I need to add some tests too.
=> fix: SourceMapper correctly uses `ModuleLoader` to get source lines

core/extension_set.rs, core/runtime/jsruntime.rs, core/runtime/snapshot.rs, core/source_map.rs
This commits updates `SourceMapper` API to be a bit more performant
by using `ModuleName` (which in case of snapshots is a `&'static str`)
instead of owned `String`.
=> perf: Make SourceMaps cheaper by using static strs

core/ops.rs
Fixes https://github.com/denoland/deno_core/issues/649
Fixes https://github.com/denoland/deno_core/issues/806
=> Don't leak CFunctionInfo and CTypeInfo

core/ops.rs, core/runtime/bindings.rs, core/runtime/jsruntime.rs
Fixes crashes caused by https://github.com/denoland/deno_core/pull/832 by making it the responsibility of `InnerIsolateState` to free the cfunctioninfo/ctypeinfo _after_ dropping the isolate, instead of the `OpCtx` freeing those on drop.
The cause of the crash is that the `OpCtx` gets dropped when the realm is destroyed (and we free the fast api info), but the isolate still lives because we don't destroy the isolate until [after destroying the realm](https://github.com/denoland/deno_core/blob/19d2d603e506b4d6b6aa1f88c092dbd59f4000b6/core/runtime/jsrealm.rs#L183-L184). In that time before we destroy the isolate, a V8 worker thread still has a reference to the dropped CFunctionInfo, and boom UAF.
Here's a proper stacktrace for the check failure
```
#
#
#
#
#FailureMessage Object: …
```
=> fix(core): Drop fast function info after isolate

Cargo.lock, Cargo.toml
rusty_v8 0.98.1 and 0.98.2 had to be yanked, because
they broke peoples' builds.
There are no functional changes, just a new release.
=> chore: upgrade rusty_v8 to 0.99.0

core/lib.rs, core/runtime/jsruntime.rs, core/source_map.rs
This trait was deprecated in https://github.com/denoland/deno_core/pull/823 and is
scheduled to be removed in 0.300.0
=> feat: Remove `SourceMapGetter` trait

core/error.rs, testing/integration/error_callsite/error_callsite.out, testing/integration/error_callsite/error_callsite.ts, testing/integration/error_non_existent_eval_source/error_non_existent_eval_source.out, testing/integration/error_non_existent_eval_source/error_non_existent_eval_source.ts, testing/lib.rs
Fixes #854. Fixes https://github.com/denoland/deno/issues/24782 once this lands there.
The first issue is pretty straightforward, I didn't realize that the `Callsite` object had a `toString` method (though in retrospect it makes sense).
The second issue is that we try to do some parsing of the eval origin so we can source map it, but if the origin wasn't in the form we expected we would return undefined instead of leaving it alone. 
So in this case
```js
const AsyncFunction = Object.getPrototypeOf(async function () {
// empty
}).constructor;
const func = new AsyncFunction(
`return doesNotExist();
//# sourceURL=empty.eval`,
);
func.call({});
```
We try to parse the `evalOrigin` (which is `"empty.eval"`) and since it's not in the expected format (the form that comes from v8 directly) we …
=> fix: Add missing `toString` to callsites, handle user provided eval origin

core/lib.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs, core/runtime/setup.rs, testing/checkin/runner/mod.rs, testing/lib.rs
Needed for https://github.com/denoland/deno/pull/24743.
=> feat: Add ImportAssertionsSupport

core/error.rs, core/runtime/bindings.rs, testing/integration/error_get_script_name_or_source_url/error_get_script_name_or_source_url.out, testing/integration/error_get_script_name_or_source_url/error_get_script_name_or_source_url.ts, testing/integration/error_prepare_stack_trace/error_prepare_stack_trace.out, testing/lib.rs
Both Chrome and Node have a `getScriptNameOrSourceUrl()` method on the `CallSite` prototype. We didn't have that which causes an error in `vitest`, see https://github.com/denoland/deno/issues/24898
=> fix: add `getScriptNameOrSourceURL` to `CallSite` prototype

core/io/buffers.rs, core/io/mod.rs, core/lib.rs
=> Remove `BufMutViewWhole`

core/modules/loaders.rs, core/runtime/jsruntime.rs
This commit adds a `ModuleLoader::purge_and_prevent_code_cache`
method that is called when a V8 warning for import assertions is received.
This is a temporary method, that will be removed after Deno 2 when 
requirement for import assertion support is dropped completely.
=> feat: Add a temporary way to warn on import assertions

core/runtime/snapshot.rs
Due to a change in Rust nightly, the Rust linter now warns when an elided lifetime ends up being a named lifetime [1]. In this case, the elided lifetime is `'static`, so we should explicitly set the lifetime to `'static`.
[1] https://github.com/rust-lang/rust/pull/129207
=> fix: explicitly set the named lifetime to static

Cargo.lock, Cargo.toml, core/runtime/jsruntime.rs, core/runtime/setup.rs, rust-toolchain.toml
Fixes: https://github.com/denoland/deno_core/issues/894
The IsolateParams `cpp_heap` option has bugs, so switch back to `attach_cpp_heap`.
=> fix: upgrade V8 to v0.106

core/modules/map.rs, core/runtime/bindings.rs
Fix for https://github.com/denoland/deno/issues/25275
This code is like hacks on top of hacks, but basically save & restore cped in the dynamic import flow.
=> fix: preserve cped in dynamic imports

core/feature_checker.rs
Closes https://github.com/denoland/deno_core/issues/901
=> feat: Remove deprecated methods from `FeatureChecker`

core/modules/map.rs, core/modules/module_map_data.rs, core/modules/tests.rs, core/runtime/bindings.rs
This patch adds a fast path for already loaded and evaluated dynamic imports by immediately resolving the promise and skipping most of the event loop machinery.
```js
// Warmup
await import('./other.mjs')
await import('./other.mjs')
await import('./other.mjs')
await import('./other.mjs')
await import('./other.mjs')
const start = Date.now()
for (let i = 0; i < 100000; i++) {
await import('./other.mjs')
}
```
=> perf: fast path for cached dyn imports

core/modules/map.rs, core/runtime/jsruntime.rs
Fixes crash reported in https://github.com/denoland/deno/issues/20610#issuecomment-2357238775
The assert was intended to mean that the promise returned from evaluate should always be settled, but instead we were asserting that the mpsc::channel never needed to be polled more than once. Also fixes an issue where we were draining the microtask queue within `op_import_sync`, which is wrong.
=> fix: remove future machiney from evaluate_sync

Cargo.lock, dcore/Cargo.toml
=> build: remove futures dep from dcore binary

core/error.rs, testing/integration/error_prepare_stack_trace_crash/error_prepare_stack_trace_crash.js, testing/lib.rs
Fix panic when a global interceptor is misconfigured or throws an exception. 
Fixes https://github.com/denoland/deno/pull/24985#issuecomment-2365460210 and https://github.com/denoland/deno/issues/26240
=> Fix panic in `prepare_stack_trace_callback` when global interceptor throws

core/error_codes.rs
Apparently anyhow's chain doesnt include the top level error, even though some resources state otherwise.
This fixes to add a fallback for the top-level error
=> fix: add top-level error fallback for get_error_code

.github/workflows/ci.yml, .github/workflows/release.yml
Something strange has happened in the past two days - even though
we use `ubuntu-latest` image, suddenly runners started using
`ubuntu-22.04` instead of `ubuntu-24.04` that was used before.
Using explicit `ubuntu-24.04` seems to fix the issue.
=> ci: use ubuntu-24.04

core/runtime/op_driver/op_results.rs
This is causing duplicate messages to show up during the efforts of https://github.com/denoland/deno/issues/26171. 
This change does not affect errors as they currently are, and also all tests in CLI (and WPT) pass locally without trouble
=> fix: use non-special formatting for OpError message

Cargo.lock, Cargo.toml
Supersedes https://github.com/denoland/deno_core/pull/937
=> chore: upgrade twox-hash to 2.0

ops/op2/dispatch_fast.rs, ops/op2/test_cases/async/async_deferred.out, ops/op2/test_cases/async/async_lazy.out, ops/op2/test_cases/sync/add.out, ops/op2/test_cases/sync/bigint.out, ops/op2/test_cases/sync/bool.out, ops/op2/test_cases/sync/bool_result.out, ops/op2/test_cases/sync/buffers.out, ops/op2/test_cases/sync/buffers_copy.out, ops/op2/test_cases/sync/cfg.out, ops/op2/test_cases/sync/clippy_allow.out, ops/op2/test_cases/sync/cppgc_resource.out, ops/op2/test_cases/sync/doc_comment.out, ops/op2/test_cases/sync/fast_alternative.out, ops/op2/test_cases/sync/generics.out, ops/op2/test_cases/sync/op_state_attr.out, ops/op2/test_cases/sync/op_state_rc.out, ops/op2/test_cases/sync/op_state_ref.out, ops/op2/test_cases/sync/result_external.out, ops/op2/test_cases/sync/result_primitive.out, ops/op2/test_cases/sync/result_scope.out, ops/op2/test_cases/sync/result_void.out, ops/op2/test_cases/sync/smi.out, ops/op2/test_cases/sync/string_cow.out, ops/op2/test_cases/sync/string_onebyte.out, ops/op2/test_cases/sync/string_owned.out, ops/op2/test_cases/sync/string_ref.out, ops/op2/test_cases/sync/v8_ref_option.out
Ref https://github.com/denoland/deno/issues/26480
Matches Rust's `as` cast (used by slow calls)
=> Clamp smi in fast calls by default

core/fast_string.rs
=> feat: `FastString` - ability to unsafely specify if string is ASCII or not

core/ops_builtin.rs
We were adding the `__esModule` export as intended, but then returning the original module instead of the wrapped one.
=> fix: return wrapped module instead of original module

core/ops_builtin_v8.rs
Reverts denoland/deno_core#922
Fixes https://github.com/denoland/deno_core/issues/951
=> Revert "Mark microtask ops fast"

Cargo.lock, core/runtime/bindings.rs, ops/Cargo.toml, ops/op2/object_wrap.rs, testing/ops.d.ts, testing/unit/resource_test.ts
`fn from_point` in Rust is exposed as `.fromPoint` in JS. I think this is better than having an explict rename attribute since that's very rare to be used.
=> Default to camelCase for object wrap ops

core/error.rs
this PR has no effect on the CLI, but exposing this allows deploy to avoid patching callsites on old deployments.
Basically in deploy, when creating the isolate I would expect something like
```rust
if !is_new_deployment {
isolate.set_prepare_stack_trace_callback(
deno_core::error::prepare_stack_trace_callback_with_original_callsites
);
}
```
=> feat: expose a version of prepare stack trace callback that doesn't patch callsites

ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs
```
error[E0308]: mismatched types
--> ext/webstorage/lib.rs:55:1
|
55  | #[op2]
| ^^^^^^
| |
| expected `&mut HandleScope<'_, ()>`, found `&mut &mut Isolate`
| arguments to this function are incorrect
|
= note: expected mutable reference `&mut HandleScope<'_, ()>`
found mutable reference `&mut &mut Isolate`
note: associated function defined here
--> /Users/divy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-130.0.1/src/string.rs:368:10
|
368 |   pub fn new_from_one_byte<'s>(
|          ^^^^^^^^^^^^^^^^^
= note: this error originates in the attribute macro `op2` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0308]: mismatched types
--> ext/webstorage/lib.rs:55:1
|
55  | #[op2]
| ^^^^^^
| |
| expected `&mut HandleScope<'_>`, found `&mut &mut Isolate`
| …
```
=> fix: borrow checker errors with isolate and object wrap usage

core/modules/map.rs
Closes https://github.com/denoland/deno_core/issues/974
=> fix: export all symbols for Wasm modules

ops/op2/config.rs, ops/op2/dispatch_slow.rs, ops/op2/mod.rs, ops/op2/object_wrap.rs, ops/op2/signature.rs, test.mjs, testing/checkin/runner/ops.rs
Equivalent to Deno's `webidl.requiredArguments` internal.
```rust
#[fast]
#[required(2)]
fn set_item(
&self,
state: &mut OpState,
#[string] key: &str,
#[string] value: &str,
) {
// ...
}
```
=> Add `#[required(<count>)]`

Cargo.lock, core/Cargo.toml, core/runtime/bindings.rs, core/runtime/ops.rs, testing/checkin/runner/ops.rs, testing/ops.d.ts, testing/unit/resource_test.ts
This is to match the default equivalent WebIDL converter. I don't know of any ops in Deno that depend on the clamping behavior.
=> Use wrapping cast for #[smi] arguments

ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, testing/checkin/runner/ops.rs, testing/checkin/runtime/object.ts, testing/ops.d.ts, testing/unit/resource_test.ts
```rust
#[fast]
fn with_varargs(
&self,
#[varargs] args: Option<&v8::FunctionCallbackArguments>,
) {
}
```
=> Support `#[varargs]` in object wrap

ops/op2/config.rs, ops/op2/mod.rs, ops/op2/object_wrap.rs, ops/op2/signature.rs, testing/checkin/runner/ops.rs, testing/ops.d.ts, testing/unit/resource_test.ts
For when auto-camelCasing isn't enough.
```rust
#[op2]
impl StatementSync {
#[rename("sourceSQL")]
fn source_sql(&self) -> String { /* ... */ }
}
```
=> Add #[rename] attribute

dcore/src/main.rs, dcore/src/metrics.rs, testing/checkin/runner/mod.rs, testing/lib.rs
Adds two flags, `--strace-ops` and `--strace-ops-summary`.
`--strace-ops` prints out events (like it does in deno)
`--strace-ops-summary` prints out a json object at the end of execution with summary stats like
```json
{
"counts": {
"op_foo": {
"fast": 10,
"slow": 1000
}
},
"completed_sync": 0,
"completed_async": 0,
"errored_sync": 0,
"errored_async": 0
}
```
Useful for checking whether you're getting fast calls
=> add `--strace-ops` flag to dcore

core/examples/ts_module_loader.rs, core/modules/loaders.rs, core/source_map.rs, testing/checkin/runner/ts_module_loader.rs
This will reduce an allocation in a refactor I'm doing for `deno compile` because we can return a static reference to the bytes.
=> refactor: ability to get borrowed source map bytes from loader

core/runtime/bindings.rs, ops/op2/mod.rs, ops/op2/object_wrap.rs, ops/op2/test_cases/sync/object_wrap.out, ops/op2/test_cases/sync/object_wrap.rs, testing/checkin/runner/ops.rs, testing/ops.d.ts, testing/unit/resource_test.ts
To support e.g.
```rust
#[op2]
impl Foo {
#[static_method]
fn foo() {}
fn foo(&self) {}
}
```
=> allow static and instance methods with same name

core/extension_set.rs, core/ops.rs, core/runtime/bindings.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, testing/unit/resource_test.ts
It is cheaper to store all OpCtx in one place and pass around OpMethodDecl and an offset that divides the OpCtx in normal ops and method ops.
=> Remove intermediate OpMethodCtx

testing/integration/error_source_maps_with_prepare_stack_trace/error_source_maps_with_prepare_stack_trace.out, testing/integration/error_source_maps_with_prepare_stack_trace/error_source_maps_with_prepare_stack_trace.ts
See https://github.com/denoland/deno_core/actions/runs/12589761265/job/35090134069
Looks like #1008 missed a file, don't know why CI passed in the PR though 🤔
=> chore: fix failing lint CI job on main

core/runtime/ops.rs
Ref https://github.com/denoland/deno/issues/27545.
Fixes a leak in deno.serve with an empty response. We would call `to_string_ptr` with an empty string and then call alloc with a length of 0 which is UB.
Instead of using `alloc` directly, which has a large number of invariants to uphold, I've changed to just use `Vec` APIs. That leaves us with fewer invariants to uphold, handles the tricky cases for us, and we need to make a `Vec` eventually anyway (since `String` just wraps a Vec).
=> fix: don't call `alloc` with a length of 0

.github/workflows/ci-lint-deps/action.yml, .github/workflows/ci-test-miri/action.yml
Pin the nightly version for now. Starting from nightly 2025-01-03, all cfg(tests) produce compiler error:
```
error: unexpected `cfg` condition name: `test`
--> ops/op2/mod.rs:363:7
|
363 | #[cfg(test)]
|       ^^^^
|
= help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `ub_checks`, `unix`, and `windows`
= help: …
```
=> ci: pin nightly to `2025-01-02`

Cargo.lock, Cargo.toml, core/cppgc.rs, core/webidl.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, ops/webidl/dictionary.rs, ops/webidl/mod.rs, ops/webidl/test_cases/dict.out, ops/webidl/test_cases/dict.rs
replaces hashmap with indexmap for records, and some minor fixes
And adds a `SameObject` utility to cppgc
=> feat(webidl): distinguish Nullable from Option, allow setting default value in webidl op2 macro attribute

core/extension_set.rs, core/extensions.rs, core/runtime/bindings.rs, ops/op2/object_wrap.rs, ops/op2/test_cases/sync/object_wrap.out, testing/checkin/runner/extensions.rs, testing/checkin/runner/ops.rs, testing/checkin/runtime/object.ts, testing/ops.d.ts, testing/unit/resource_test.ts
Use the default template when no constructor is defined.
=> Allow object wrap without constructor

core/webidl.rs, ops/op2/dispatch_slow.rs, ops/op2/test_cases/sync/webidl.out, ops/webidl/dictionary.rs, ops/webidl/enum.rs, ops/webidl/mod.rs, ops/webidl/test_cases/dict.out, ops/webidl/test_cases/enum.out
Avoids re-instantiating the converters with different generic arguments, saving on binary size.
=> perf: dynamically dispatch context function in `WebIDLConverter`

core/error.rs
This is the previous behaviour which was unexpected and we want to change this to actually throw the correct error, however this is breaking a few things in CLI so reverting this single change for now and will revisit at a later date
=> fix: revert js_class_and_message_to_exception to just do TypeErrors

core/01_core.js, testing/unit/error_test.ts
This PR adds support of the 2nd arguments (`options`) to JS error constructors (`BadResource`, `Interrupted`, and `NotCapable`). closes #1031
By this change, downstream implementations can use `cause` option of `Error` class.
=> feat: support options in error constructors

ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, testing/checkin/runner/ops.rs, testing/ops.d.ts, testing/unit/resource_test.ts
Example usage:
```rust
#[op2]
impl UnsafePointerView {
#[cppgc]
fn get_context(&self, #[this] this: v8::Global<v8::Object>) -> GPUCanvasContext {
GPUCanvasContext { view: this }
}
}
struct GPUCanvasContext {
view: v8::Global<v8::Object>,
}
#[op2]
impl GPUCanvasContext {
fn canvas(&self) -> v8::Global<v8::Object> { self.view.clone() }
}
```
`#[this]` works on both slow and fast calls.
=> Add `#[this] _: v8::Global<v8::Object>`

core/runtime/bindings.rs, testing/checkin/runner/ops.rs
The template cannot be modified after a new instance via `tmpl.get_function()` is created. This patch defers async method registration to happen after other ops.
=> fix: obj wrap async method registration

core/modules/tests.rs, core/runtime/bindings.rs
Fixes https://github.com/denoland/deno_core/issues/1050
=> Handle dyn imports exceeding call stack size

core/01_core.js
Please take a look at PR: https://github.com/denoland/deno/pull/27789
This change will help to expose fd to server when a socket connection is established.
=> fix(ext/net): node compatibility issue, expose fd using internal symbol in deno_core

Cargo.lock, Cargo.toml, core/error.rs, core/inspector.rs, core/lib.rs, core/modules/loaders.rs, core/modules/mod.rs, core/modules/tests.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs
Wires up the code cache through the `ExtModuleLoader` and extension initialization, so that embedders can use the V8 code cache on extension sources.
=> feat: optional code cache for extension sources

core/arena/unique_arena.rs, core/runtime/op_driver/erased_future.rs, core/runtime/op_driver/future_arena.rs
This PR fixes some aliasing bugs caused by improper usage of shared and mutable references intermixed with raw pointer accesses. These have been discovered by running the testsuite under [Tree Borrows](https://www.ralfj.de/blog/2023/06/02/tree-borrows.html), a new aliasing model for Rust and a potential replacement for Stacked Borrows. While TB is in general more lenient than SB, there are some cases where it is more strict due to SB relying on gross hacks, which have been removed from TB.
Turns out that `deno_core` relied on such hacks. The problem is with the `DynFutureInfoErased`, which has arbitrary data that is being modified by a future while other references to it are held in the runtime. To prevent this, that is put into an `UnsafeCell` which makes such modifications allowed.
But …
=> Fix aliasing bugs revealed by Tree Borrows

core/01_core.js, core/ops_builtin.rs, core/ops_builtin_v8.rs, core/runtime/bindings.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/snapshot.rs
this can be used to extend the api surface for ext modules without the overhead of assigning new data to each one. in particular, to add contextual logging (https://github.com/denoland/deno/pull/28562)
=> feat: add import.meta proto for ext modules

core/io/resource.rs, core/ops.rs, core/ops_builtin.rs, core/runtime/jsrealm.rs, core/runtime/jsruntime.rs, core/runtime/mod.rs, ops/op2/config.rs, ops/op2/dispatch_async.rs, testing/checkin/runner/extensions.rs, testing/checkin/runner/ops_async.rs, testing/checkin/runner/ops_io.rs, testing/checkin/runtime/async.ts, testing/unit/ops_async_test.ts, testing/unit/resource_test.ts
Adds a `unrefed_resources` hashset similar to `unrefed_ops` and `#[op2(async, promise_id)]` for `op_read`, `op_read_all`, `op_write`. 
This allows ref'ing and unrefing using resource handles instead of inflight promises, similar to `uv_ref` and `uv_unref` in libuv. Useful for implementing `HandleWrap` in Deno.
=> Ref'ing read and writes on resource handles

core/runtime/bindings.rs, testing/unit/resource_test.ts
Needed for Node compat.
Ref https://github.com/nodejs/node/commit/64348f5ea557d414b08d1b2602d794e48ac06bb2
=> Remove prototypes of object wrap methods

core/ops_builtin.rs
This works towards fixing [#27730](https://github.com/denoland/deno/issues/27730) and [#21091](https://github.com/denoland/deno/issues/21091).
An error is not handled when calling `op_is_terminal`.
Ironically, this causes the application to panic when bootstrapping if there is no terminal in windows.
This PR does not fully fix the issue yet, as there is a similar problem in deno's code base, see this [pull request](https://github.com/denoland/deno/pull/28823).
=> fix(compile): panic when calling op_is_terminal

core/benches/ops/async.rs, core/benches/ops/sync.rs, core/benches/snapshot/snapshot.rs, core/error.rs, core/examples/op2.rs, core/examples/snapshot/build.rs, core/examples/snapshot/src/main.rs, core/extension_set.rs, core/extensions.rs, core/modules/tests.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, core/runtime/snapshot.rs, core/runtime/tests/error.rs, core/runtime/tests/jsrealm.rs, core/runtime/tests/misc.rs, core/runtime/tests/mod.rs, core/runtime/tests/ops.rs, core/runtime/tests/snapshot.rs, testing/checkin/runner/mod.rs, testing/checkin/runner/snapshot.rs, testing/checkin/runner/testing.rs
track set of extensions in snapshot so that initialization cannot be misused. makes extension use simpler too.
```
load snapshot/plain     time:   [1.2286 ms 1.2341 ms 1.2396 ms]
change: [-0.8270% +0.1529% +1.3241%] (p = 0.81 > 0.05)
No change in performance detected.
Found 2 outliers among 50 measurements (4.00%)
2 (4.00%) high severe
load snapshot/transpiled
time:   [1.2247 ms 1.2299 ms 1.2358 ms]
change: [-1.0111% -0.0696% +0.9278%] (p = 0.89 > 0.05)
No change in performance detected.
Found 4 outliers among 50 measurements (8.00%)
```
=> feat: extensions track esm initialization automatically

dcore/src/main.rs, testing/checkin/runner/mod.rs, testing/checkin/runner/ops_worker.rs, testing/checkin/runner/testing.rs
pulled from debugging the v8 upgrade, this just lets you run worker tests directly in dcore.
=> fix: spawn workers correctly in dcore

core/error.rs, core/extension_set.rs, core/extensions.rs, core/lib.rs, core/runtime/jsruntime.rs, core/runtime/tests/jsrealm.rs
Allows something like this:
```rust
let extensions = vec![
my_cool_ext::lazy_init(),
];
let js_runtime = JsRuntime::new(Options { extensions, .. });
js_runtime.lazy_init_extensions(vec![
my_cool_ext::args(a, b),
]);
```
=> feat: lazy extension initialization

Cargo.lock, Cargo.toml, core/cppgc.rs, core/extension_set.rs, core/extensions.rs, core/runtime/bindings.rs, core/runtime/jsruntime.rs, core/runtime/ops.rs, core/runtime/setup.rs, core/runtime/snapshot.rs, ops/op2/test_cases/async/async_cppgc.rs, ops/op2/test_cases/sync/cppgc_resource.rs, ops/op2/test_cases/sync/object_wrap.rs, ops/op2/test_cases_fail/lifetimes.rs, testing/checkin/runner/ops.rs, testing/checkin/runner/ops_async.rs, testing/checkin/runner/ops_worker.rs
in 13.6 the cppgc heap is automatically created, so we can remove our initialization for it.
=> feat: upgrade V8 to 137

Cargo.lock, Cargo.toml, core/00_infra.js, core/error.rs
currently js errors that are printed via console.log in cli display their additional properties, however the same does not apply for when displayed from rust. this allows for `fmt_errors.rs` in cli to change that.
=> feat: add `additional_properties` to `JsError`

core/lib.rs, core/runtime/ops_rust_to_v8.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/signature.rs, testing/checkin/runner/ops.rs, testing/ops.d.ts, testing/unit/resource_test.ts
Currently the only alternative is `UndefinedOption<T>` in webidl which isn't fast-compatible. This PR adds a fast API-compatible `#[undefined]` return type attribute.
=> Add `#[undefined]` ret type marker

ops/op2/dispatch_slow.rs, ops/op2/signature.rs, testing/unit/resource_test.ts
Apparently `assertEquals` is not strict enough, replaced with a normal `assert`
=> fix: `#[undefined]` attribute

core/Cargo.toml, core/runtime/tests/misc.rs
Fixes https://github.com/denoland/deno/issues/29059
Messages from the inspector that hold a number value can result in the loss of floating point precision when deserialized.
When a user sends `0.9999999999999999` in the REPL, V8 returns a [RemoteObject](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-RemoteObject) that contains the field `"value": 0.9999999999999999`. However, when it's deserialized into `serde_json::Value` here:
https://github.com/denoland/deno_core/blob/fc1ef37491950e82d2fb2e5e426a55723e730ce1/core/inspector.rs#L883-L884
`value` becomes `serde_json::Number(1.0)`, causing the REPL to print `1`. Enabling the `float_roundtrip` feature flag of serde json resolves this.
Before:
After:
=> fix(inspector): Preserve floating point precision from inspector response

Cargo.toml
Caused a valgrind failure on main.
Reverts denoland/deno_core#1026
=> Revert "chore: sync release profile overrides with cli"

core/error.rs, core/ops_builtin_v8.rs
Currently, the function to terminate a process when an exception occurs can only be accessed from JS (ops). I would like to make it accessible from Rust as well for https://github.com/denoland/deno/pull/30128.
=> feat: expose dispatch_exception function

.github/workflows/ci-job.yml, .github/workflows/ci-test/action.yml, ops/op2/test_cases_fail/lifetimes.rs, ops/op2/test_cases_fail/lifetimes.stderr
Reverting some of the changes from https://github.com/denoland/deno_core/pull/1187,
that were blocking the V8 upgrade but resulted in removal of debug symbols for Windows.
=> fix: restore debug symbols for Windows

core/extensions.rs, core/runtime/tests/misc.rs
Made it so parameters make it to middleware (if no parameters then middleware is unchanged)
=> Middleware support for Parameters
